package coder.aihui.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table AZYS__MX.
 */
@Entity
public class AZYS_MX {

    private String ITEM_NAME;

    @Id
    private Long ITEM_ID;

    private boolean isChecked;

    @Generated(hash = 2120523856)
    public AZYS_MX(String ITEM_NAME, Long ITEM_ID, boolean isChecked) {
        this.ITEM_NAME = ITEM_NAME;
        this.ITEM_ID = ITEM_ID;
        this.isChecked = isChecked;
    }

    @Generated(hash = 1940819008)
    public AZYS_MX() {
    }

    public String getITEM_NAME() {
        return this.ITEM_NAME;
    }

    public void setITEM_NAME(String ITEM_NAME) {
        this.ITEM_NAME = ITEM_NAME;
    }

    public Long getITEM_ID() {
        return this.ITEM_ID;
    }

    public void setITEM_ID(Long ITEM_ID) {
        this.ITEM_ID = ITEM_ID;
    }

    public boolean getIsChecked() {
        return this.isChecked;
    }

    public void setIsChecked(boolean isChecked) {
        this.isChecked = isChecked;
    }



}
