package coder.aihui.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 


import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;

/**
 * Entity mapped to table CORRECT__ASSET.
 */


@Entity
public class CORRECT_ASSET  {
    @Id
    @Property(nameInDb = "ID")
    private Long           ID;
    private String         DDID;
    private String         DDMC;
    private String         GHDWID;
    private String         GHDWMC;
    private String         PPID;
    private String         PPMC;
    private String         SCCJID;
    private String         SCCJMC;
    private String         GGXH;
    private String         SCBH;
    private Integer        PP_FLAG;
    private Integer        GHDW_FLAG;
    private Integer        SCCJ_FLAG;
    private Integer        DD_FLAG;
    private String         USERID;
    private String         USERNAME;
    private Integer        IS_UP;
    private java.util.Date SCRQ;
    private String         WZMC;
    private String         FRONT_PIC;
    private String         SIDE_PIC;
    private String         BIG_FRONT_PIC;
    private String         BIG_SIDE_PIC;
    private Integer        ZMZ_FILE_ID;
    private Integer        CMZ_FILE_ID;
    private String         QD_FLAG;
    private String         BGRID;
    private String         BGRXM;
    private String         BGKSID;
    private String         BGKSMC;
    private String         BIG_MP_PIC;
    private String         MP_PIC;
    private String         BQLX;
    private Integer        QRBZ;
    private String         BQYCZT;
    private String         BQZT;
    @Generated(hash = 1093449408)
    public CORRECT_ASSET(Long ID, String DDID, String DDMC, String GHDWID, String GHDWMC, String PPID,
            String PPMC, String SCCJID, String SCCJMC, String GGXH, String SCBH, Integer PP_FLAG,
            Integer GHDW_FLAG, Integer SCCJ_FLAG, Integer DD_FLAG, String USERID, String USERNAME,
            Integer IS_UP, java.util.Date SCRQ, String WZMC, String FRONT_PIC, String SIDE_PIC,
            String BIG_FRONT_PIC, String BIG_SIDE_PIC, Integer ZMZ_FILE_ID, Integer CMZ_FILE_ID,
            String QD_FLAG, String BGRID, String BGRXM, String BGKSID, String BGKSMC, String BIG_MP_PIC,
            String MP_PIC, String BQLX, Integer QRBZ, String BQYCZT, String BQZT) {
        this.ID = ID;
        this.DDID = DDID;
        this.DDMC = DDMC;
        this.GHDWID = GHDWID;
        this.GHDWMC = GHDWMC;
        this.PPID = PPID;
        this.PPMC = PPMC;
        this.SCCJID = SCCJID;
        this.SCCJMC = SCCJMC;
        this.GGXH = GGXH;
        this.SCBH = SCBH;
        this.PP_FLAG = PP_FLAG;
        this.GHDW_FLAG = GHDW_FLAG;
        this.SCCJ_FLAG = SCCJ_FLAG;
        this.DD_FLAG = DD_FLAG;
        this.USERID = USERID;
        this.USERNAME = USERNAME;
        this.IS_UP = IS_UP;
        this.SCRQ = SCRQ;
        this.WZMC = WZMC;
        this.FRONT_PIC = FRONT_PIC;
        this.SIDE_PIC = SIDE_PIC;
        this.BIG_FRONT_PIC = BIG_FRONT_PIC;
        this.BIG_SIDE_PIC = BIG_SIDE_PIC;
        this.ZMZ_FILE_ID = ZMZ_FILE_ID;
        this.CMZ_FILE_ID = CMZ_FILE_ID;
        this.QD_FLAG = QD_FLAG;
        this.BGRID = BGRID;
        this.BGRXM = BGRXM;
        this.BGKSID = BGKSID;
        this.BGKSMC = BGKSMC;
        this.BIG_MP_PIC = BIG_MP_PIC;
        this.MP_PIC = MP_PIC;
        this.BQLX = BQLX;
        this.QRBZ = QRBZ;
        this.BQYCZT = BQYCZT;
        this.BQZT = BQZT;
    }
    @Generated(hash = 10135895)
    public CORRECT_ASSET() {
    }
    public Long getID() {
        return this.ID;
    }
    public void setID(Long ID) {
        this.ID = ID;
    }
    public String getDDID() {
        return this.DDID;
    }
    public void setDDID(String DDID) {
        this.DDID = DDID;
    }
    public String getDDMC() {
        return this.DDMC;
    }
    public void setDDMC(String DDMC) {
        this.DDMC = DDMC;
    }
    public String getGHDWID() {
        return this.GHDWID;
    }
    public void setGHDWID(String GHDWID) {
        this.GHDWID = GHDWID;
    }
    public String getGHDWMC() {
        return this.GHDWMC;
    }
    public void setGHDWMC(String GHDWMC) {
        this.GHDWMC = GHDWMC;
    }
    public String getPPID() {
        return this.PPID;
    }
    public void setPPID(String PPID) {
        this.PPID = PPID;
    }
    public String getPPMC() {
        return this.PPMC;
    }
    public void setPPMC(String PPMC) {
        this.PPMC = PPMC;
    }
    public String getSCCJID() {
        return this.SCCJID;
    }
    public void setSCCJID(String SCCJID) {
        this.SCCJID = SCCJID;
    }
    public String getSCCJMC() {
        return this.SCCJMC;
    }
    public void setSCCJMC(String SCCJMC) {
        this.SCCJMC = SCCJMC;
    }
    public String getGGXH() {
        return this.GGXH;
    }
    public void setGGXH(String GGXH) {
        this.GGXH = GGXH;
    }
    public String getSCBH() {
        return this.SCBH;
    }
    public void setSCBH(String SCBH) {
        this.SCBH = SCBH;
    }
    public Integer getPP_FLAG() {
        return this.PP_FLAG;
    }
    public void setPP_FLAG(Integer PP_FLAG) {
        this.PP_FLAG = PP_FLAG;
    }
    public Integer getGHDW_FLAG() {
        return this.GHDW_FLAG;
    }
    public void setGHDW_FLAG(Integer GHDW_FLAG) {
        this.GHDW_FLAG = GHDW_FLAG;
    }
    public Integer getSCCJ_FLAG() {
        return this.SCCJ_FLAG;
    }
    public void setSCCJ_FLAG(Integer SCCJ_FLAG) {
        this.SCCJ_FLAG = SCCJ_FLAG;
    }
    public Integer getDD_FLAG() {
        return this.DD_FLAG;
    }
    public void setDD_FLAG(Integer DD_FLAG) {
        this.DD_FLAG = DD_FLAG;
    }
    public String getUSERID() {
        return this.USERID;
    }
    public void setUSERID(String USERID) {
        this.USERID = USERID;
    }
    public String getUSERNAME() {
        return this.USERNAME;
    }
    public void setUSERNAME(String USERNAME) {
        this.USERNAME = USERNAME;
    }
    public Integer getIS_UP() {
        return this.IS_UP;
    }
    public void setIS_UP(Integer IS_UP) {
        this.IS_UP = IS_UP;
    }
    public java.util.Date getSCRQ() {
        return this.SCRQ;
    }
    public void setSCRQ(java.util.Date SCRQ) {
        this.SCRQ = SCRQ;
    }
    public String getWZMC() {
        return this.WZMC;
    }
    public void setWZMC(String WZMC) {
        this.WZMC = WZMC;
    }
    public String getFRONT_PIC() {
        return this.FRONT_PIC;
    }
    public void setFRONT_PIC(String FRONT_PIC) {
        this.FRONT_PIC = FRONT_PIC;
    }
    public String getSIDE_PIC() {
        return this.SIDE_PIC;
    }
    public void setSIDE_PIC(String SIDE_PIC) {
        this.SIDE_PIC = SIDE_PIC;
    }
    public String getBIG_FRONT_PIC() {
        return this.BIG_FRONT_PIC;
    }
    public void setBIG_FRONT_PIC(String BIG_FRONT_PIC) {
        this.BIG_FRONT_PIC = BIG_FRONT_PIC;
    }
    public String getBIG_SIDE_PIC() {
        return this.BIG_SIDE_PIC;
    }
    public void setBIG_SIDE_PIC(String BIG_SIDE_PIC) {
        this.BIG_SIDE_PIC = BIG_SIDE_PIC;
    }
    public Integer getZMZ_FILE_ID() {
        return this.ZMZ_FILE_ID;
    }
    public void setZMZ_FILE_ID(Integer ZMZ_FILE_ID) {
        this.ZMZ_FILE_ID = ZMZ_FILE_ID;
    }
    public Integer getCMZ_FILE_ID() {
        return this.CMZ_FILE_ID;
    }
    public void setCMZ_FILE_ID(Integer CMZ_FILE_ID) {
        this.CMZ_FILE_ID = CMZ_FILE_ID;
    }
    public String getQD_FLAG() {
        return this.QD_FLAG;
    }
    public void setQD_FLAG(String QD_FLAG) {
        this.QD_FLAG = QD_FLAG;
    }
    public String getBGRID() {
        return this.BGRID;
    }
    public void setBGRID(String BGRID) {
        this.BGRID = BGRID;
    }
    public String getBGRXM() {
        return this.BGRXM;
    }
    public void setBGRXM(String BGRXM) {
        this.BGRXM = BGRXM;
    }
    public String getBGKSID() {
        return this.BGKSID;
    }
    public void setBGKSID(String BGKSID) {
        this.BGKSID = BGKSID;
    }
    public String getBGKSMC() {
        return this.BGKSMC;
    }
    public void setBGKSMC(String BGKSMC) {
        this.BGKSMC = BGKSMC;
    }
    public String getBIG_MP_PIC() {
        return this.BIG_MP_PIC;
    }
    public void setBIG_MP_PIC(String BIG_MP_PIC) {
        this.BIG_MP_PIC = BIG_MP_PIC;
    }
    public String getMP_PIC() {
        return this.MP_PIC;
    }
    public void setMP_PIC(String MP_PIC) {
        this.MP_PIC = MP_PIC;
    }
    public String getBQLX() {
        return this.BQLX;
    }
    public void setBQLX(String BQLX) {
        this.BQLX = BQLX;
    }
    public Integer getQRBZ() {
        return this.QRBZ;
    }
    public void setQRBZ(Integer QRBZ) {
        this.QRBZ = QRBZ;
    }
    public String getBQYCZT() {
        return this.BQYCZT;
    }
    public void setBQYCZT(String BQYCZT) {
        this.BQYCZT = BQYCZT;
    }
    public String getBQZT() {
        return this.BQZT;
    }
    public void setBQZT(String BQZT) {
        this.BQZT = BQZT;
    }

   
}
