package coder.aihui.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;
import org.greenrobot.greendao.annotation.Transient;

/**
 * Entity mapped to table IN__ASSET.
 */

@Entity
public class IN_ASSET {
    @Id
    @Property(nameInDb = "ID")
    private Long           ID;
    private String         ZZID;
    private String         KFID;
    private String         FLID;
    private String         ZBID;
    private String         ZBMC;
    private String         HSID;
    private String         HSMC;
    private String         KPBH;
    private String         KPBH_OLD;
    private String         UHF;
    private String         UHF1;
    private String         UHF2;                //旧资产id
    private String         UFH3;
    private String         MCGGID;
    private String         WZMC;
    private String         GGXH;
    private String         ZXDW;
    private String         KCID;
    private String         KSID;
    private String         KSMC;
    private String         BGKSID;
    private String         BGKSMC;
    private String         BGRID;
    private String         BGRXM;
    private String         JBRID;
    private String         JBRXM;
    private String         CDID;
    private String         CDMC;
    private String         PPID;
    private String         PPMC;
    private String         GHDWID;
    private String         GHDWMC;
    private String         SCCJID;
    private String         SCCJMC;
    private String         GRTJ;
    private java.util.Date GRRQ;
    private String         ZT;
    private java.util.Date SYRQ;
    private java.util.Date JZRQ;
    private java.util.Date DHAZRQ;
    private String         DDXX;
    private String         DDID;
    private String         DDMC;
    private String         DDJC;
    private Double         ZJYS;
    private Double         LJZJYS;
    private Double         SYYS;
    private Double         DJ;
    private Double         CZ_JE;
    private Double         ZC_JE;
    private Double         KY_JE;
    private Double         CZ_LJZJJE;
    private Double         ZC_LJZJJE;
    private Double         KY_LJZJJE;
    private Double         LJZJJE;
    private Double         JCZ;
    private String         KJQJ;
    private String         RKDMXID;
    private String         RKD_DJHM;
    private java.util.Date RKRQ;
    private String         RKDMXID2;
    private String         RKD_DJHM2;
    private java.util.Date RKRQ2;
    private String         CKDMXID;
    private String         CKD_DJHM;
    private java.util.Date CKRQ;
    private String         CKDMXID2;
    private String         CKD_DJHM2;
    private java.util.Date CKRQ2;
    private java.util.Date DBSRQ;
    private String         BSDMXID;
    private String         BSD_DJHM;
    private java.util.Date BSRQ;
    private String         JFLBID;
    private String         JFLBMC;
    private String         JFID;
    private String         JFMC;
    private String         SCBH;
    private Integer        PM_PLAN_FLAG;
    private Integer        PM_FLAG;
    private Integer        WXBZ;
    private Double         TD_TDMJ;
    private String         TD_ZH;
    private java.util.Date TD_FZRQ;
    private String         TD_LY;
    private String         TD_CQXS;
    private String         TD_SYFX;
    private String         QC_CPH;
    private java.util.Date QC_FZRQ;
    private String         QC_ZH;
    private String         QC_XH;
    private Double         QC_PQL;
    private String         FW_JZJG;
    private Double         FW_JZMJ;
    private java.util.Date FW_JGRQ;
    private java.util.Date FW_SYRQ;
    private String         LRRID;
    private String         LRRXM;
    private java.util.Date LRRQ;
    private String         SHRID;
    private String         SHRXM;
    private java.util.Date SHRQ;
    private Integer        SHBZ;
    private String         BZ;
    private Integer        TZXZ;
    private Integer        ZFBZ;
    private java.util.Date ZFSJ;
    private String         ZFRID;
    private String         ZFRXM;
    private java.util.Date BXRQ;
    private String         CCXLH;
    private java.util.Date SCRQ;
    private String         JLBZ;
    private String         RFID_CODE;
    private Integer        PRINT_COUNT;
    private String         FACTORY_PHONE;
    private String         KSKCID;
    private String         BAR_CODE;
    private Integer        XJBZ;
    private Integer        QJBZ;

    @Transient
    private boolean flagChoose; //是否打钩



    @Transient
    private Integer whichType;        //1已盘 2未盘 3变 4转

    @Transient
    private String change_dept;
    @Transient
    private String is__change;
    @Transient
    private String dqddmc;
    @Generated(hash = 1013639575)
    public IN_ASSET(Long ID, String ZZID, String KFID, String FLID, String ZBID, String ZBMC,
            String HSID, String HSMC, String KPBH, String KPBH_OLD, String UHF, String UHF1,
            String UHF2, String UFH3, String MCGGID, String WZMC, String GGXH, String ZXDW, String KCID,
            String KSID, String KSMC, String BGKSID, String BGKSMC, String BGRID, String BGRXM,
            String JBRID, String JBRXM, String CDID, String CDMC, String PPID, String PPMC,
            String GHDWID, String GHDWMC, String SCCJID, String SCCJMC, String GRTJ,
            java.util.Date GRRQ, String ZT, java.util.Date SYRQ, java.util.Date JZRQ,
            java.util.Date DHAZRQ, String DDXX, String DDID, String DDMC, String DDJC, Double ZJYS,
            Double LJZJYS, Double SYYS, Double DJ, Double CZ_JE, Double ZC_JE, Double KY_JE,
            Double CZ_LJZJJE, Double ZC_LJZJJE, Double KY_LJZJJE, Double LJZJJE, Double JCZ,
            String KJQJ, String RKDMXID, String RKD_DJHM, java.util.Date RKRQ, String RKDMXID2,
            String RKD_DJHM2, java.util.Date RKRQ2, String CKDMXID, String CKD_DJHM,
            java.util.Date CKRQ, String CKDMXID2, String CKD_DJHM2, java.util.Date CKRQ2,
            java.util.Date DBSRQ, String BSDMXID, String BSD_DJHM, java.util.Date BSRQ, String JFLBID,
            String JFLBMC, String JFID, String JFMC, String SCBH, Integer PM_PLAN_FLAG, Integer PM_FLAG,
            Integer WXBZ, Double TD_TDMJ, String TD_ZH, java.util.Date TD_FZRQ, String TD_LY,
            String TD_CQXS, String TD_SYFX, String QC_CPH, java.util.Date QC_FZRQ, String QC_ZH,
            String QC_XH, Double QC_PQL, String FW_JZJG, Double FW_JZMJ, java.util.Date FW_JGRQ,
            java.util.Date FW_SYRQ, String LRRID, String LRRXM, java.util.Date LRRQ, String SHRID,
            String SHRXM, java.util.Date SHRQ, Integer SHBZ, String BZ, Integer TZXZ, Integer ZFBZ,
            java.util.Date ZFSJ, String ZFRID, String ZFRXM, java.util.Date BXRQ, String CCXLH,
            java.util.Date SCRQ, String JLBZ, String RFID_CODE, Integer PRINT_COUNT,
            String FACTORY_PHONE, String KSKCID, String BAR_CODE, Integer XJBZ, Integer QJBZ) {
        this.ID = ID;
        this.ZZID = ZZID;
        this.KFID = KFID;
        this.FLID = FLID;
        this.ZBID = ZBID;
        this.ZBMC = ZBMC;
        this.HSID = HSID;
        this.HSMC = HSMC;
        this.KPBH = KPBH;
        this.KPBH_OLD = KPBH_OLD;
        this.UHF = UHF;
        this.UHF1 = UHF1;
        this.UHF2 = UHF2;
        this.UFH3 = UFH3;
        this.MCGGID = MCGGID;
        this.WZMC = WZMC;
        this.GGXH = GGXH;
        this.ZXDW = ZXDW;
        this.KCID = KCID;
        this.KSID = KSID;
        this.KSMC = KSMC;
        this.BGKSID = BGKSID;
        this.BGKSMC = BGKSMC;
        this.BGRID = BGRID;
        this.BGRXM = BGRXM;
        this.JBRID = JBRID;
        this.JBRXM = JBRXM;
        this.CDID = CDID;
        this.CDMC = CDMC;
        this.PPID = PPID;
        this.PPMC = PPMC;
        this.GHDWID = GHDWID;
        this.GHDWMC = GHDWMC;
        this.SCCJID = SCCJID;
        this.SCCJMC = SCCJMC;
        this.GRTJ = GRTJ;
        this.GRRQ = GRRQ;
        this.ZT = ZT;
        this.SYRQ = SYRQ;
        this.JZRQ = JZRQ;
        this.DHAZRQ = DHAZRQ;
        this.DDXX = DDXX;
        this.DDID = DDID;
        this.DDMC = DDMC;
        this.DDJC = DDJC;
        this.ZJYS = ZJYS;
        this.LJZJYS = LJZJYS;
        this.SYYS = SYYS;
        this.DJ = DJ;
        this.CZ_JE = CZ_JE;
        this.ZC_JE = ZC_JE;
        this.KY_JE = KY_JE;
        this.CZ_LJZJJE = CZ_LJZJJE;
        this.ZC_LJZJJE = ZC_LJZJJE;
        this.KY_LJZJJE = KY_LJZJJE;
        this.LJZJJE = LJZJJE;
        this.JCZ = JCZ;
        this.KJQJ = KJQJ;
        this.RKDMXID = RKDMXID;
        this.RKD_DJHM = RKD_DJHM;
        this.RKRQ = RKRQ;
        this.RKDMXID2 = RKDMXID2;
        this.RKD_DJHM2 = RKD_DJHM2;
        this.RKRQ2 = RKRQ2;
        this.CKDMXID = CKDMXID;
        this.CKD_DJHM = CKD_DJHM;
        this.CKRQ = CKRQ;
        this.CKDMXID2 = CKDMXID2;
        this.CKD_DJHM2 = CKD_DJHM2;
        this.CKRQ2 = CKRQ2;
        this.DBSRQ = DBSRQ;
        this.BSDMXID = BSDMXID;
        this.BSD_DJHM = BSD_DJHM;
        this.BSRQ = BSRQ;
        this.JFLBID = JFLBID;
        this.JFLBMC = JFLBMC;
        this.JFID = JFID;
        this.JFMC = JFMC;
        this.SCBH = SCBH;
        this.PM_PLAN_FLAG = PM_PLAN_FLAG;
        this.PM_FLAG = PM_FLAG;
        this.WXBZ = WXBZ;
        this.TD_TDMJ = TD_TDMJ;
        this.TD_ZH = TD_ZH;
        this.TD_FZRQ = TD_FZRQ;
        this.TD_LY = TD_LY;
        this.TD_CQXS = TD_CQXS;
        this.TD_SYFX = TD_SYFX;
        this.QC_CPH = QC_CPH;
        this.QC_FZRQ = QC_FZRQ;
        this.QC_ZH = QC_ZH;
        this.QC_XH = QC_XH;
        this.QC_PQL = QC_PQL;
        this.FW_JZJG = FW_JZJG;
        this.FW_JZMJ = FW_JZMJ;
        this.FW_JGRQ = FW_JGRQ;
        this.FW_SYRQ = FW_SYRQ;
        this.LRRID = LRRID;
        this.LRRXM = LRRXM;
        this.LRRQ = LRRQ;
        this.SHRID = SHRID;
        this.SHRXM = SHRXM;
        this.SHRQ = SHRQ;
        this.SHBZ = SHBZ;
        this.BZ = BZ;
        this.TZXZ = TZXZ;
        this.ZFBZ = ZFBZ;
        this.ZFSJ = ZFSJ;
        this.ZFRID = ZFRID;
        this.ZFRXM = ZFRXM;
        this.BXRQ = BXRQ;
        this.CCXLH = CCXLH;
        this.SCRQ = SCRQ;
        this.JLBZ = JLBZ;
        this.RFID_CODE = RFID_CODE;
        this.PRINT_COUNT = PRINT_COUNT;
        this.FACTORY_PHONE = FACTORY_PHONE;
        this.KSKCID = KSKCID;
        this.BAR_CODE = BAR_CODE;
        this.XJBZ = XJBZ;
        this.QJBZ = QJBZ;
    }
    @Generated(hash = 1130900203)
    public IN_ASSET() {
    }
    public Long getID() {
        return this.ID;
    }
    public void setID(Long ID) {
        this.ID = ID;
    }
    public String getZZID() {
        return this.ZZID;
    }
    public void setZZID(String ZZID) {
        this.ZZID = ZZID;
    }
    public String getKFID() {
        return this.KFID;
    }
    public void setKFID(String KFID) {
        this.KFID = KFID;
    }
    public String getFLID() {
        return this.FLID;
    }
    public void setFLID(String FLID) {
        this.FLID = FLID;
    }
    public String getZBID() {
        return this.ZBID;
    }
    public void setZBID(String ZBID) {
        this.ZBID = ZBID;
    }
    public String getZBMC() {
        return this.ZBMC;
    }
    public void setZBMC(String ZBMC) {
        this.ZBMC = ZBMC;
    }
    public String getHSID() {
        return this.HSID;
    }
    public void setHSID(String HSID) {
        this.HSID = HSID;
    }
    public String getHSMC() {
        return this.HSMC;
    }
    public void setHSMC(String HSMC) {
        this.HSMC = HSMC;
    }
    public String getKPBH() {
        return this.KPBH;
    }
    public void setKPBH(String KPBH) {
        this.KPBH = KPBH;
    }
    public String getKPBH_OLD() {
        return this.KPBH_OLD;
    }
    public void setKPBH_OLD(String KPBH_OLD) {
        this.KPBH_OLD = KPBH_OLD;
    }
    public String getUHF() {
        return this.UHF;
    }
    public void setUHF(String UHF) {
        this.UHF = UHF;
    }
    public String getUHF1() {
        return this.UHF1;
    }
    public void setUHF1(String UHF1) {
        this.UHF1 = UHF1;
    }
    public String getUHF2() {
        return this.UHF2;
    }
    public void setUHF2(String UHF2) {
        this.UHF2 = UHF2;
    }
    public String getUFH3() {
        return this.UFH3;
    }
    public void setUFH3(String UFH3) {
        this.UFH3 = UFH3;
    }
    public String getMCGGID() {
        return this.MCGGID;
    }
    public void setMCGGID(String MCGGID) {
        this.MCGGID = MCGGID;
    }
    public String getWZMC() {
        return this.WZMC;
    }
    public void setWZMC(String WZMC) {
        this.WZMC = WZMC;
    }
    public String getGGXH() {
        return this.GGXH;
    }
    public void setGGXH(String GGXH) {
        this.GGXH = GGXH;
    }
    public String getZXDW() {
        return this.ZXDW;
    }
    public void setZXDW(String ZXDW) {
        this.ZXDW = ZXDW;
    }
    public String getKCID() {
        return this.KCID;
    }
    public void setKCID(String KCID) {
        this.KCID = KCID;
    }
    public String getKSID() {
        return this.KSID;
    }
    public void setKSID(String KSID) {
        this.KSID = KSID;
    }
    public String getKSMC() {
        return this.KSMC;
    }
    public void setKSMC(String KSMC) {
        this.KSMC = KSMC;
    }
    public String getBGKSID() {
        return this.BGKSID;
    }
    public void setBGKSID(String BGKSID) {
        this.BGKSID = BGKSID;
    }
    public String getBGKSMC() {
        return this.BGKSMC;
    }
    public void setBGKSMC(String BGKSMC) {
        this.BGKSMC = BGKSMC;
    }
    public String getBGRID() {
        return this.BGRID;
    }
    public void setBGRID(String BGRID) {
        this.BGRID = BGRID;
    }
    public String getBGRXM() {
        return this.BGRXM;
    }
    public void setBGRXM(String BGRXM) {
        this.BGRXM = BGRXM;
    }
    public String getJBRID() {
        return this.JBRID;
    }
    public void setJBRID(String JBRID) {
        this.JBRID = JBRID;
    }
    public String getJBRXM() {
        return this.JBRXM;
    }
    public void setJBRXM(String JBRXM) {
        this.JBRXM = JBRXM;
    }
    public String getCDID() {
        return this.CDID;
    }
    public void setCDID(String CDID) {
        this.CDID = CDID;
    }
    public String getCDMC() {
        return this.CDMC;
    }
    public void setCDMC(String CDMC) {
        this.CDMC = CDMC;
    }
    public String getPPID() {
        return this.PPID;
    }
    public void setPPID(String PPID) {
        this.PPID = PPID;
    }
    public String getPPMC() {
        return this.PPMC;
    }
    public void setPPMC(String PPMC) {
        this.PPMC = PPMC;
    }
    public String getGHDWID() {
        return this.GHDWID;
    }
    public void setGHDWID(String GHDWID) {
        this.GHDWID = GHDWID;
    }
    public String getGHDWMC() {
        return this.GHDWMC;
    }
    public void setGHDWMC(String GHDWMC) {
        this.GHDWMC = GHDWMC;
    }
    public String getSCCJID() {
        return this.SCCJID;
    }
    public void setSCCJID(String SCCJID) {
        this.SCCJID = SCCJID;
    }
    public String getSCCJMC() {
        return this.SCCJMC;
    }
    public void setSCCJMC(String SCCJMC) {
        this.SCCJMC = SCCJMC;
    }
    public String getGRTJ() {
        return this.GRTJ;
    }
    public void setGRTJ(String GRTJ) {
        this.GRTJ = GRTJ;
    }
    public java.util.Date getGRRQ() {
        return this.GRRQ;
    }
    public void setGRRQ(java.util.Date GRRQ) {
        this.GRRQ = GRRQ;
    }
    public String getZT() {
        return this.ZT;
    }
    public void setZT(String ZT) {
        this.ZT = ZT;
    }
    public java.util.Date getSYRQ() {
        return this.SYRQ;
    }
    public void setSYRQ(java.util.Date SYRQ) {
        this.SYRQ = SYRQ;
    }
    public java.util.Date getJZRQ() {
        return this.JZRQ;
    }
    public void setJZRQ(java.util.Date JZRQ) {
        this.JZRQ = JZRQ;
    }
    public java.util.Date getDHAZRQ() {
        return this.DHAZRQ;
    }
    public void setDHAZRQ(java.util.Date DHAZRQ) {
        this.DHAZRQ = DHAZRQ;
    }
    public String getDDXX() {
        return this.DDXX;
    }
    public void setDDXX(String DDXX) {
        this.DDXX = DDXX;
    }
    public String getDDID() {
        return this.DDID;
    }
    public void setDDID(String DDID) {
        this.DDID = DDID;
    }
    public String getDDMC() {
        return this.DDMC;
    }
    public void setDDMC(String DDMC) {
        this.DDMC = DDMC;
    }
    public String getDDJC() {
        return this.DDJC;
    }
    public void setDDJC(String DDJC) {
        this.DDJC = DDJC;
    }
    public Double getZJYS() {
        return this.ZJYS;
    }
    public void setZJYS(Double ZJYS) {
        this.ZJYS = ZJYS;
    }
    public Double getLJZJYS() {
        return this.LJZJYS;
    }
    public void setLJZJYS(Double LJZJYS) {
        this.LJZJYS = LJZJYS;
    }
    public Double getSYYS() {
        return this.SYYS;
    }
    public void setSYYS(Double SYYS) {
        this.SYYS = SYYS;
    }
    public Double getDJ() {
        return this.DJ;
    }
    public void setDJ(Double DJ) {
        this.DJ = DJ;
    }
    public Double getCZ_JE() {
        return this.CZ_JE;
    }
    public void setCZ_JE(Double CZ_JE) {
        this.CZ_JE = CZ_JE;
    }
    public Double getZC_JE() {
        return this.ZC_JE;
    }
    public void setZC_JE(Double ZC_JE) {
        this.ZC_JE = ZC_JE;
    }
    public Double getKY_JE() {
        return this.KY_JE;
    }
    public void setKY_JE(Double KY_JE) {
        this.KY_JE = KY_JE;
    }
    public Double getCZ_LJZJJE() {
        return this.CZ_LJZJJE;
    }
    public void setCZ_LJZJJE(Double CZ_LJZJJE) {
        this.CZ_LJZJJE = CZ_LJZJJE;
    }
    public Double getZC_LJZJJE() {
        return this.ZC_LJZJJE;
    }
    public void setZC_LJZJJE(Double ZC_LJZJJE) {
        this.ZC_LJZJJE = ZC_LJZJJE;
    }
    public Double getKY_LJZJJE() {
        return this.KY_LJZJJE;
    }
    public void setKY_LJZJJE(Double KY_LJZJJE) {
        this.KY_LJZJJE = KY_LJZJJE;
    }
    public Double getLJZJJE() {
        return this.LJZJJE;
    }
    public void setLJZJJE(Double LJZJJE) {
        this.LJZJJE = LJZJJE;
    }
    public Double getJCZ() {
        return this.JCZ;
    }
    public void setJCZ(Double JCZ) {
        this.JCZ = JCZ;
    }
    public String getKJQJ() {
        return this.KJQJ;
    }
    public void setKJQJ(String KJQJ) {
        this.KJQJ = KJQJ;
    }
    public String getRKDMXID() {
        return this.RKDMXID;
    }
    public void setRKDMXID(String RKDMXID) {
        this.RKDMXID = RKDMXID;
    }
    public String getRKD_DJHM() {
        return this.RKD_DJHM;
    }
    public void setRKD_DJHM(String RKD_DJHM) {
        this.RKD_DJHM = RKD_DJHM;
    }
    public java.util.Date getRKRQ() {
        return this.RKRQ;
    }
    public void setRKRQ(java.util.Date RKRQ) {
        this.RKRQ = RKRQ;
    }
    public String getRKDMXID2() {
        return this.RKDMXID2;
    }
    public void setRKDMXID2(String RKDMXID2) {
        this.RKDMXID2 = RKDMXID2;
    }
    public String getRKD_DJHM2() {
        return this.RKD_DJHM2;
    }
    public void setRKD_DJHM2(String RKD_DJHM2) {
        this.RKD_DJHM2 = RKD_DJHM2;
    }
    public java.util.Date getRKRQ2() {
        return this.RKRQ2;
    }
    public void setRKRQ2(java.util.Date RKRQ2) {
        this.RKRQ2 = RKRQ2;
    }
    public String getCKDMXID() {
        return this.CKDMXID;
    }
    public void setCKDMXID(String CKDMXID) {
        this.CKDMXID = CKDMXID;
    }
    public String getCKD_DJHM() {
        return this.CKD_DJHM;
    }
    public void setCKD_DJHM(String CKD_DJHM) {
        this.CKD_DJHM = CKD_DJHM;
    }
    public java.util.Date getCKRQ() {
        return this.CKRQ;
    }
    public void setCKRQ(java.util.Date CKRQ) {
        this.CKRQ = CKRQ;
    }
    public String getCKDMXID2() {
        return this.CKDMXID2;
    }
    public void setCKDMXID2(String CKDMXID2) {
        this.CKDMXID2 = CKDMXID2;
    }
    public String getCKD_DJHM2() {
        return this.CKD_DJHM2;
    }
    public void setCKD_DJHM2(String CKD_DJHM2) {
        this.CKD_DJHM2 = CKD_DJHM2;
    }
    public java.util.Date getCKRQ2() {
        return this.CKRQ2;
    }
    public void setCKRQ2(java.util.Date CKRQ2) {
        this.CKRQ2 = CKRQ2;
    }
    public java.util.Date getDBSRQ() {
        return this.DBSRQ;
    }
    public void setDBSRQ(java.util.Date DBSRQ) {
        this.DBSRQ = DBSRQ;
    }
    public String getBSDMXID() {
        return this.BSDMXID;
    }
    public void setBSDMXID(String BSDMXID) {
        this.BSDMXID = BSDMXID;
    }
    public String getBSD_DJHM() {
        return this.BSD_DJHM;
    }
    public void setBSD_DJHM(String BSD_DJHM) {
        this.BSD_DJHM = BSD_DJHM;
    }
    public java.util.Date getBSRQ() {
        return this.BSRQ;
    }
    public void setBSRQ(java.util.Date BSRQ) {
        this.BSRQ = BSRQ;
    }
    public String getJFLBID() {
        return this.JFLBID;
    }
    public void setJFLBID(String JFLBID) {
        this.JFLBID = JFLBID;
    }
    public String getJFLBMC() {
        return this.JFLBMC;
    }
    public void setJFLBMC(String JFLBMC) {
        this.JFLBMC = JFLBMC;
    }
    public String getJFID() {
        return this.JFID;
    }
    public void setJFID(String JFID) {
        this.JFID = JFID;
    }
    public String getJFMC() {
        return this.JFMC;
    }
    public void setJFMC(String JFMC) {
        this.JFMC = JFMC;
    }
    public String getSCBH() {
        return this.SCBH;
    }
    public void setSCBH(String SCBH) {
        this.SCBH = SCBH;
    }
    public Integer getPM_PLAN_FLAG() {
        return this.PM_PLAN_FLAG;
    }
    public void setPM_PLAN_FLAG(Integer PM_PLAN_FLAG) {
        this.PM_PLAN_FLAG = PM_PLAN_FLAG;
    }
    public Integer getPM_FLAG() {
        return this.PM_FLAG;
    }
    public void setPM_FLAG(Integer PM_FLAG) {
        this.PM_FLAG = PM_FLAG;
    }
    public Integer getWXBZ() {
        return this.WXBZ;
    }
    public void setWXBZ(Integer WXBZ) {
        this.WXBZ = WXBZ;
    }
    public Double getTD_TDMJ() {
        return this.TD_TDMJ;
    }
    public void setTD_TDMJ(Double TD_TDMJ) {
        this.TD_TDMJ = TD_TDMJ;
    }
    public String getTD_ZH() {
        return this.TD_ZH;
    }
    public void setTD_ZH(String TD_ZH) {
        this.TD_ZH = TD_ZH;
    }
    public java.util.Date getTD_FZRQ() {
        return this.TD_FZRQ;
    }
    public void setTD_FZRQ(java.util.Date TD_FZRQ) {
        this.TD_FZRQ = TD_FZRQ;
    }
    public String getTD_LY() {
        return this.TD_LY;
    }
    public void setTD_LY(String TD_LY) {
        this.TD_LY = TD_LY;
    }
    public String getTD_CQXS() {
        return this.TD_CQXS;
    }
    public void setTD_CQXS(String TD_CQXS) {
        this.TD_CQXS = TD_CQXS;
    }
    public String getTD_SYFX() {
        return this.TD_SYFX;
    }
    public void setTD_SYFX(String TD_SYFX) {
        this.TD_SYFX = TD_SYFX;
    }
    public String getQC_CPH() {
        return this.QC_CPH;
    }
    public void setQC_CPH(String QC_CPH) {
        this.QC_CPH = QC_CPH;
    }
    public java.util.Date getQC_FZRQ() {
        return this.QC_FZRQ;
    }
    public void setQC_FZRQ(java.util.Date QC_FZRQ) {
        this.QC_FZRQ = QC_FZRQ;
    }
    public String getQC_ZH() {
        return this.QC_ZH;
    }
    public void setQC_ZH(String QC_ZH) {
        this.QC_ZH = QC_ZH;
    }
    public String getQC_XH() {
        return this.QC_XH;
    }
    public void setQC_XH(String QC_XH) {
        this.QC_XH = QC_XH;
    }
    public Double getQC_PQL() {
        return this.QC_PQL;
    }
    public void setQC_PQL(Double QC_PQL) {
        this.QC_PQL = QC_PQL;
    }
    public String getFW_JZJG() {
        return this.FW_JZJG;
    }
    public void setFW_JZJG(String FW_JZJG) {
        this.FW_JZJG = FW_JZJG;
    }
    public Double getFW_JZMJ() {
        return this.FW_JZMJ;
    }
    public void setFW_JZMJ(Double FW_JZMJ) {
        this.FW_JZMJ = FW_JZMJ;
    }
    public java.util.Date getFW_JGRQ() {
        return this.FW_JGRQ;
    }
    public void setFW_JGRQ(java.util.Date FW_JGRQ) {
        this.FW_JGRQ = FW_JGRQ;
    }
    public java.util.Date getFW_SYRQ() {
        return this.FW_SYRQ;
    }
    public void setFW_SYRQ(java.util.Date FW_SYRQ) {
        this.FW_SYRQ = FW_SYRQ;
    }
    public String getLRRID() {
        return this.LRRID;
    }
    public void setLRRID(String LRRID) {
        this.LRRID = LRRID;
    }
    public String getLRRXM() {
        return this.LRRXM;
    }
    public void setLRRXM(String LRRXM) {
        this.LRRXM = LRRXM;
    }
    public java.util.Date getLRRQ() {
        return this.LRRQ;
    }
    public void setLRRQ(java.util.Date LRRQ) {
        this.LRRQ = LRRQ;
    }
    public String getSHRID() {
        return this.SHRID;
    }
    public void setSHRID(String SHRID) {
        this.SHRID = SHRID;
    }
    public String getSHRXM() {
        return this.SHRXM;
    }
    public void setSHRXM(String SHRXM) {
        this.SHRXM = SHRXM;
    }
    public java.util.Date getSHRQ() {
        return this.SHRQ;
    }
    public void setSHRQ(java.util.Date SHRQ) {
        this.SHRQ = SHRQ;
    }
    public Integer getSHBZ() {
        return this.SHBZ;
    }
    public void setSHBZ(Integer SHBZ) {
        this.SHBZ = SHBZ;
    }
    public String getBZ() {
        return this.BZ;
    }
    public void setBZ(String BZ) {
        this.BZ = BZ;
    }
    public Integer getTZXZ() {
        return this.TZXZ;
    }
    public void setTZXZ(Integer TZXZ) {
        this.TZXZ = TZXZ;
    }
    public Integer getZFBZ() {
        return this.ZFBZ;
    }
    public void setZFBZ(Integer ZFBZ) {
        this.ZFBZ = ZFBZ;
    }
    public java.util.Date getZFSJ() {
        return this.ZFSJ;
    }
    public void setZFSJ(java.util.Date ZFSJ) {
        this.ZFSJ = ZFSJ;
    }
    public String getZFRID() {
        return this.ZFRID;
    }
    public void setZFRID(String ZFRID) {
        this.ZFRID = ZFRID;
    }
    public String getZFRXM() {
        return this.ZFRXM;
    }
    public void setZFRXM(String ZFRXM) {
        this.ZFRXM = ZFRXM;
    }
    public java.util.Date getBXRQ() {
        return this.BXRQ;
    }
    public void setBXRQ(java.util.Date BXRQ) {
        this.BXRQ = BXRQ;
    }
    public String getCCXLH() {
        return this.CCXLH;
    }
    public void setCCXLH(String CCXLH) {
        this.CCXLH = CCXLH;
    }
    public java.util.Date getSCRQ() {
        return this.SCRQ;
    }
    public void setSCRQ(java.util.Date SCRQ) {
        this.SCRQ = SCRQ;
    }
    public String getJLBZ() {
        return this.JLBZ;
    }
    public void setJLBZ(String JLBZ) {
        this.JLBZ = JLBZ;
    }
    public String getRFID_CODE() {
        return this.RFID_CODE;
    }
    public void setRFID_CODE(String RFID_CODE) {
        this.RFID_CODE = RFID_CODE;
    }
    public Integer getPRINT_COUNT() {
        return this.PRINT_COUNT;
    }
    public void setPRINT_COUNT(Integer PRINT_COUNT) {
        this.PRINT_COUNT = PRINT_COUNT;
    }
    public String getFACTORY_PHONE() {
        return this.FACTORY_PHONE;
    }
    public void setFACTORY_PHONE(String FACTORY_PHONE) {
        this.FACTORY_PHONE = FACTORY_PHONE;
    }
    public String getKSKCID() {
        return this.KSKCID;
    }
    public void setKSKCID(String KSKCID) {
        this.KSKCID = KSKCID;
    }
    public String getBAR_CODE() {
        return this.BAR_CODE;
    }
    public void setBAR_CODE(String BAR_CODE) {
        this.BAR_CODE = BAR_CODE;
    }
    public Integer getXJBZ() {
        return this.XJBZ;
    }
    public void setXJBZ(Integer XJBZ) {
        this.XJBZ = XJBZ;
    }
    public Integer getQJBZ() {
        return this.QJBZ;
    }
    public void setQJBZ(Integer QJBZ) {
        this.QJBZ = QJBZ;
    }


    public boolean isFlagChoose() {
        return flagChoose;
    }

    public IN_ASSET setFlagChoose(boolean flagChoose) {
        this.flagChoose = flagChoose;
        return this;
    }



    public Integer getWhichType() {
        return whichType;
    }

    public IN_ASSET setWhichType(Integer whichType) {
        this.whichType = whichType;
        return this;
    }

    public String getChange_dept() {
        return change_dept;
    }

    public IN_ASSET setChange_dept(String change_dept) {
        this.change_dept = change_dept;
        return this;
    }

    public String getIs__change() {
        return is__change;
    }

    public IN_ASSET setIs__change(String is__change) {
        this.is__change = is__change;
        return this;
    }

    public String getDqddmc() {
        return dqddmc;
    }

    public IN_ASSET setDqddmc(String dqddmc) {
        this.dqddmc = dqddmc;
        return this;
    }
}
