package coder.aihui.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.mcxtzhang.indexlib.IndexBar.bean.BaseIndexPinyinBean;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Transient;

/**
 * Entity mapped to table IN__MATERIALS__PPMC.
 */
@Entity
public class IN_MATERIALS_PPMC extends BaseIndexPinyinBean {

    @Id
    private Long ID;
    private String DM;
    private String MC;
    private String LB;

    @Transient
    private boolean IS_CHECKED;

    @Generated(hash = 889378287)
    public IN_MATERIALS_PPMC(Long ID, String DM, String MC, String LB) {
        this.ID = ID;
        this.DM = DM;
        this.MC = MC;
        this.LB = LB;
    }
    @Generated(hash = 566421468)
    public IN_MATERIALS_PPMC() {
    }

    @Override
    public String getTarget() {
        return MC;
    }

    public Long getID() {
        return this.ID;
    }
    public void setID(Long ID) {
        this.ID = ID;
    }
    public String getDM() {
        return this.DM;
    }
    public void setDM(String DM) {
        this.DM = DM;
    }
    public String getMC() {
        return this.MC;
    }
    public void setMC(String MC) {
        this.MC = MC;
    }
    public String getLB() {
        return this.LB;
    }
    public void setLB(String LB) {
        this.LB = LB;
    }

    public boolean getIS_CHECKED() {
        return IS_CHECKED;
    }

    public void setIS_CHECKED(boolean IS_CHECKED) {
        this.IS_CHECKED = IS_CHECKED;
    }
}
