package coder.aihui.data.bean;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.


@Entity
public class IN_STORE_QC {
    @Id
    @Property(nameInDb = "QCID")
    private Long QCID;
    private String QCKS;
    private String QCDL;
    private String QCPC;
    private String QCKF;
    private Integer QCZT;
    private Integer QC_UPDATE_USER;
    private Integer QC_CREATE_USER;
    private java.util.Date QC_CREATE_DATE;
    private java.util.Date QC_UPDATE_DATE;
    private java.util.Date QCJSSJ;
    private java.util.Date QCKSSJ;
    @Generated(hash = 2083430357)
    public IN_STORE_QC(Long QCID, String QCKS, String QCDL, String QCPC, String QCKF, Integer QCZT,
            Integer QC_UPDATE_USER, Integer QC_CREATE_USER, java.util.Date QC_CREATE_DATE,
            java.util.Date QC_UPDATE_DATE, java.util.Date QCJSSJ, java.util.Date QCKSSJ) {
        this.QCID = QCID;
        this.QCKS = QCKS;
        this.QCDL = QCDL;
        this.QCPC = QCPC;
        this.QCKF = QCKF;
        this.QCZT = QCZT;
        this.QC_UPDATE_USER = QC_UPDATE_USER;
        this.QC_CREATE_USER = QC_CREATE_USER;
        this.QC_CREATE_DATE = QC_CREATE_DATE;
        this.QC_UPDATE_DATE = QC_UPDATE_DATE;
        this.QCJSSJ = QCJSSJ;
        this.QCKSSJ = QCKSSJ;
    }
    @Generated(hash = 820425434)
    public IN_STORE_QC() {
    }
    public Long getQCID() {
        return this.QCID;
    }
    public void setQCID(Long QCID) {
        this.QCID = QCID;
    }
    public String getQCKS() {
        return this.QCKS;
    }
    public void setQCKS(String QCKS) {
        this.QCKS = QCKS;
    }
    public String getQCDL() {
        return this.QCDL;
    }
    public void setQCDL(String QCDL) {
        this.QCDL = QCDL;
    }
    public String getQCPC() {
        return this.QCPC;
    }
    public void setQCPC(String QCPC) {
        this.QCPC = QCPC;
    }
    public String getQCKF() {
        return this.QCKF;
    }
    public void setQCKF(String QCKF) {
        this.QCKF = QCKF;
    }
    public Integer getQCZT() {
        return this.QCZT;
    }
    public void setQCZT(Integer QCZT) {
        this.QCZT = QCZT;
    }
    public Integer getQC_UPDATE_USER() {
        return this.QC_UPDATE_USER;
    }
    public void setQC_UPDATE_USER(Integer QC_UPDATE_USER) {
        this.QC_UPDATE_USER = QC_UPDATE_USER;
    }
    public Integer getQC_CREATE_USER() {
        return this.QC_CREATE_USER;
    }
    public void setQC_CREATE_USER(Integer QC_CREATE_USER) {
        this.QC_CREATE_USER = QC_CREATE_USER;
    }
    public java.util.Date getQC_CREATE_DATE() {
        return this.QC_CREATE_DATE;
    }
    public void setQC_CREATE_DATE(java.util.Date QC_CREATE_DATE) {
        this.QC_CREATE_DATE = QC_CREATE_DATE;
    }
    public java.util.Date getQC_UPDATE_DATE() {
        return this.QC_UPDATE_DATE;
    }
    public void setQC_UPDATE_DATE(java.util.Date QC_UPDATE_DATE) {
        this.QC_UPDATE_DATE = QC_UPDATE_DATE;
    }
    public java.util.Date getQCJSSJ() {
        return this.QCJSSJ;
    }
    public void setQCJSSJ(java.util.Date QCJSSJ) {
        this.QCJSSJ = QCJSSJ;
    }
    public java.util.Date getQCKSSJ() {
        return this.QCKSSJ;
    }
    public void setQCKSSJ(java.util.Date QCKSSJ) {
        this.QCKSSJ = QCKSSJ;
    }



}
