package coder.aihui.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Unique;

import java.util.Date;

/**
 * Entity mapped to table INSPECT__PLAN.
 */
@Entity
public class INSPECT_PLAN {


    /**
     * 添加这个是因为 我想将临时做的数据 保存到计划当中 不作乱  保证只有一个类用于显示
     */
    @Id
    private Long ID;
    @Unique
    private Long    INSP_ID;
    private String  INSP_EXEC_TYPE;
    private String  INSP_FK_ID;
    private String  INSP_TYPE;
    private Date    INSP_EXEC_DATE;
    private Date    INSP_PRIOR_EXEC_DATE;
    private String  INSP_STATE;
    private Integer INSP_IS_DEL;
    private String  INSP_REMARK;
    private Date    INSP_CREATE_DATE;
    private Integer INSP_CREATE_USER;
    private Date    INSP_UPDATE_DATE;
    private Integer INSP_UPDATE_USER;
    private Integer INST_FK_ID;
    private String  KPBH;
    private Long    DDID;
    private String  DDMC;
    private String  WZMC;
    private String  ZQLX;
    private Long    XJFL;
    private String  XJFL_MC;
    private String  INSE_CYCLE;
    private String  RFID_CODE;
    private String  BAR_CODE;
    private Integer ISCHECK;
    private Integer RESULT;
    private Date    DOWN_DATE;
    private Date    INSP_EXEC_DATE_END;
    private String  KPBH_OLD;
    private Long    KSID;
    private Integer INSE_CYCLE_FLOAT;
    private Date    INSP_EXEC_START_DATE;
    private Date    INSP_EXEC_END_DATE;
    private String  KSMC;
    private String  SCBH;
    private String  GGXH;
    private String  PPMC;

    private Long INSE_TEMPLATE_ID;      //模板表
    private Date CREATE_DATE;
    private Date MODIFY_DATE;

    private String KFID;       //库房id

    private Boolean IS_TEMPORARY;   //是否是临时的



    @Generated(hash = 1521999701)
    public INSPECT_PLAN(Long ID, Long INSP_ID, String INSP_EXEC_TYPE, String INSP_FK_ID,
            String INSP_TYPE, Date INSP_EXEC_DATE, Date INSP_PRIOR_EXEC_DATE, String INSP_STATE,
            Integer INSP_IS_DEL, String INSP_REMARK, Date INSP_CREATE_DATE, Integer INSP_CREATE_USER,
            Date INSP_UPDATE_DATE, Integer INSP_UPDATE_USER, Integer INST_FK_ID, String KPBH, Long DDID,
            String DDMC, String WZMC, String ZQLX, Long XJFL, String XJFL_MC, String INSE_CYCLE,
            String RFID_CODE, String BAR_CODE, Integer ISCHECK, Integer RESULT, Date DOWN_DATE,
            Date INSP_EXEC_DATE_END, String KPBH_OLD, Long KSID, Integer INSE_CYCLE_FLOAT,
            Date INSP_EXEC_START_DATE, Date INSP_EXEC_END_DATE, String KSMC, String SCBH, String GGXH,
            String PPMC, Long INSE_TEMPLATE_ID, Date CREATE_DATE, Date MODIFY_DATE, String KFID,
            Boolean IS_TEMPORARY) {
        this.ID = ID;
        this.INSP_ID = INSP_ID;
        this.INSP_EXEC_TYPE = INSP_EXEC_TYPE;
        this.INSP_FK_ID = INSP_FK_ID;
        this.INSP_TYPE = INSP_TYPE;
        this.INSP_EXEC_DATE = INSP_EXEC_DATE;
        this.INSP_PRIOR_EXEC_DATE = INSP_PRIOR_EXEC_DATE;
        this.INSP_STATE = INSP_STATE;
        this.INSP_IS_DEL = INSP_IS_DEL;
        this.INSP_REMARK = INSP_REMARK;
        this.INSP_CREATE_DATE = INSP_CREATE_DATE;
        this.INSP_CREATE_USER = INSP_CREATE_USER;
        this.INSP_UPDATE_DATE = INSP_UPDATE_DATE;
        this.INSP_UPDATE_USER = INSP_UPDATE_USER;
        this.INST_FK_ID = INST_FK_ID;
        this.KPBH = KPBH;
        this.DDID = DDID;
        this.DDMC = DDMC;
        this.WZMC = WZMC;
        this.ZQLX = ZQLX;
        this.XJFL = XJFL;
        this.XJFL_MC = XJFL_MC;
        this.INSE_CYCLE = INSE_CYCLE;
        this.RFID_CODE = RFID_CODE;
        this.BAR_CODE = BAR_CODE;
        this.ISCHECK = ISCHECK;
        this.RESULT = RESULT;
        this.DOWN_DATE = DOWN_DATE;
        this.INSP_EXEC_DATE_END = INSP_EXEC_DATE_END;
        this.KPBH_OLD = KPBH_OLD;
        this.KSID = KSID;
        this.INSE_CYCLE_FLOAT = INSE_CYCLE_FLOAT;
        this.INSP_EXEC_START_DATE = INSP_EXEC_START_DATE;
        this.INSP_EXEC_END_DATE = INSP_EXEC_END_DATE;
        this.KSMC = KSMC;
        this.SCBH = SCBH;
        this.GGXH = GGXH;
        this.PPMC = PPMC;
        this.INSE_TEMPLATE_ID = INSE_TEMPLATE_ID;
        this.CREATE_DATE = CREATE_DATE;
        this.MODIFY_DATE = MODIFY_DATE;
        this.KFID = KFID;
        this.IS_TEMPORARY = IS_TEMPORARY;
    }

    @Generated(hash = 1643941457)
    public INSPECT_PLAN() {
    }

    public Long getINSP_ID() {
        return this.INSP_ID;
    }

    public void setINSP_ID(Long INSP_ID) {
        this.INSP_ID = INSP_ID;
    }

    public String getINSP_EXEC_TYPE() {
        return this.INSP_EXEC_TYPE;
    }

    public void setINSP_EXEC_TYPE(String INSP_EXEC_TYPE) {
        this.INSP_EXEC_TYPE = INSP_EXEC_TYPE;
    }

    public String getINSP_FK_ID() {
        return this.INSP_FK_ID;
    }

    public void setINSP_FK_ID(String INSP_FK_ID) {
        this.INSP_FK_ID = INSP_FK_ID;
    }

    public String getINSP_TYPE() {
        return this.INSP_TYPE;
    }

    public void setINSP_TYPE(String INSP_TYPE) {
        this.INSP_TYPE = INSP_TYPE;
    }

    public Date getINSP_EXEC_DATE() {
        return this.INSP_EXEC_DATE;
    }

    public void setINSP_EXEC_DATE(Date INSP_EXEC_DATE) {
        this.INSP_EXEC_DATE = INSP_EXEC_DATE;
    }

    public Date getINSP_PRIOR_EXEC_DATE() {
        return this.INSP_PRIOR_EXEC_DATE;
    }

    public void setINSP_PRIOR_EXEC_DATE(Date INSP_PRIOR_EXEC_DATE) {
        this.INSP_PRIOR_EXEC_DATE = INSP_PRIOR_EXEC_DATE;
    }

    public String getINSP_STATE() {
        return this.INSP_STATE;
    }

    public void setINSP_STATE(String INSP_STATE) {
        this.INSP_STATE = INSP_STATE;
    }

    public Integer getINSP_IS_DEL() {
        return this.INSP_IS_DEL;
    }

    public void setINSP_IS_DEL(Integer INSP_IS_DEL) {
        this.INSP_IS_DEL = INSP_IS_DEL;
    }

    public String getINSP_REMARK() {
        return this.INSP_REMARK;
    }

    public void setINSP_REMARK(String INSP_REMARK) {
        this.INSP_REMARK = INSP_REMARK;
    }

    public Date getINSP_CREATE_DATE() {
        return this.INSP_CREATE_DATE;
    }

    public void setINSP_CREATE_DATE(Date INSP_CREATE_DATE) {
        this.INSP_CREATE_DATE = INSP_CREATE_DATE;
    }

    public Integer getINSP_CREATE_USER() {
        return this.INSP_CREATE_USER;
    }

    public void setINSP_CREATE_USER(Integer INSP_CREATE_USER) {
        this.INSP_CREATE_USER = INSP_CREATE_USER;
    }

    public Date getINSP_UPDATE_DATE() {
        return this.INSP_UPDATE_DATE;
    }

    public void setINSP_UPDATE_DATE(Date INSP_UPDATE_DATE) {
        this.INSP_UPDATE_DATE = INSP_UPDATE_DATE;
    }

    public Integer getINSP_UPDATE_USER() {
        return this.INSP_UPDATE_USER;
    }

    public void setINSP_UPDATE_USER(Integer INSP_UPDATE_USER) {
        this.INSP_UPDATE_USER = INSP_UPDATE_USER;
    }

    public Integer getINST_FK_ID() {
        return this.INST_FK_ID;
    }

    public void setINST_FK_ID(Integer INST_FK_ID) {
        this.INST_FK_ID = INST_FK_ID;
    }

    public String getKPBH() {
        return this.KPBH;
    }

    public void setKPBH(String KPBH) {
        this.KPBH = KPBH;
    }

    public Long getDDID() {
        return this.DDID;
    }

    public void setDDID(Long DDID) {
        this.DDID = DDID;
    }

    public String getDDMC() {
        return this.DDMC;
    }

    public void setDDMC(String DDMC) {
        this.DDMC = DDMC;
    }

    public String getWZMC() {
        return this.WZMC;
    }

    public void setWZMC(String WZMC) {
        this.WZMC = WZMC;
    }

    public String getZQLX() {
        return this.ZQLX;
    }

    public void setZQLX(String ZQLX) {
        this.ZQLX = ZQLX;
    }

    public Long getXJFL() {
        return this.XJFL;
    }

    public void setXJFL(Long XJFL) {
        this.XJFL = XJFL;
    }

    public String getXJFL_MC() {
        return this.XJFL_MC;
    }

    public void setXJFL_MC(String XJFL_MC) {
        this.XJFL_MC = XJFL_MC;
    }

    public String getINSE_CYCLE() {
        return this.INSE_CYCLE;
    }

    public void setINSE_CYCLE(String INSE_CYCLE) {
        this.INSE_CYCLE = INSE_CYCLE;
    }

    public String getRFID_CODE() {
        return this.RFID_CODE;
    }

    public void setRFID_CODE(String RFID_CODE) {
        this.RFID_CODE = RFID_CODE;
    }

    public String getBAR_CODE() {
        return this.BAR_CODE;
    }

    public void setBAR_CODE(String BAR_CODE) {
        this.BAR_CODE = BAR_CODE;
    }

    public Integer getISCHECK() {
        return this.ISCHECK;
    }

    public void setISCHECK(Integer ISCHECK) {
        this.ISCHECK = ISCHECK;
    }

    public Integer getRESULT() {
        return this.RESULT;
    }

    public void setRESULT(Integer RESULT) {
        this.RESULT = RESULT;
    }

    public Date getDOWN_DATE() {
        return this.DOWN_DATE;
    }

    public void setDOWN_DATE(Date DOWN_DATE) {
        this.DOWN_DATE = DOWN_DATE;
    }

    public Date getINSP_EXEC_DATE_END() {
        return this.INSP_EXEC_DATE_END;
    }

    public void setINSP_EXEC_DATE_END(Date INSP_EXEC_DATE_END) {
        this.INSP_EXEC_DATE_END = INSP_EXEC_DATE_END;
    }

    public String getKPBH_OLD() {
        return this.KPBH_OLD;
    }

    public void setKPBH_OLD(String KPBH_OLD) {
        this.KPBH_OLD = KPBH_OLD;
    }

    public Long getKSID() {
        return this.KSID;
    }

    public void setKSID(Long KSID) {
        this.KSID = KSID;
    }

    public Integer getINSE_CYCLE_FLOAT() {
        return this.INSE_CYCLE_FLOAT;
    }

    public void setINSE_CYCLE_FLOAT(Integer INSE_CYCLE_FLOAT) {
        this.INSE_CYCLE_FLOAT = INSE_CYCLE_FLOAT;
    }

    public Date getINSP_EXEC_START_DATE() {
        return this.INSP_EXEC_START_DATE;
    }

    public void setINSP_EXEC_START_DATE(Date INSP_EXEC_START_DATE) {
        this.INSP_EXEC_START_DATE = INSP_EXEC_START_DATE;
    }

    public Date getINSP_EXEC_END_DATE() {
        return this.INSP_EXEC_END_DATE;
    }

    public void setINSP_EXEC_END_DATE(Date INSP_EXEC_END_DATE) {
        this.INSP_EXEC_END_DATE = INSP_EXEC_END_DATE;
    }

    public String getKSMC() {
        return this.KSMC;
    }

    public void setKSMC(String KSMC) {
        this.KSMC = KSMC;
    }

    public String getSCBH() {
        return this.SCBH;
    }

    public void setSCBH(String SCBH) {
        this.SCBH = SCBH;
    }

    public String getGGXH() {
        return this.GGXH;
    }

    public void setGGXH(String GGXH) {
        this.GGXH = GGXH;
    }

    public String getPPMC() {
        return this.PPMC;
    }

    public void setPPMC(String PPMC) {
        this.PPMC = PPMC;
    }

    public Long getINSE_TEMPLATE_ID() {
        return this.INSE_TEMPLATE_ID;
    }

    public void setINSE_TEMPLATE_ID(Long INSE_TEMPLATE_ID) {
        this.INSE_TEMPLATE_ID = INSE_TEMPLATE_ID;
    }

    public Date getCREATE_DATE() {
        return this.CREATE_DATE;
    }

    public void setCREATE_DATE(Date CREATE_DATE) {
        this.CREATE_DATE = CREATE_DATE;
    }

    public Date getMODIFY_DATE() {
        return this.MODIFY_DATE;
    }

    public void setMODIFY_DATE(Date MODIFY_DATE) {
        this.MODIFY_DATE = MODIFY_DATE;
    }

    public String getKFID() {
        return this.KFID;
    }

    public void setKFID(String KFID) {
        this.KFID = KFID;
    }

    public Boolean getIS_TEMPORARY() {
        return this.IS_TEMPORARY;
    }

    public void setIS_TEMPORARY(Boolean IS_TEMPORARY) {
        this.IS_TEMPORARY = IS_TEMPORARY;
    }

    public Long getID() {
        return this.ID;
    }

    public void setID(Long ID) {
        this.ID = ID;
    }




}
