package coder.aihui.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

/**
 * Entity mapped to table INSPECT__GROUP.
 */
@Entity
public class INSPECT_GROUP extends MyEntity {
    @Id
    private Long   ID;
    private Long   INSG_ID;
    private String INSG_KPBH;
    private String INSG_RFID;
    private String INSG_BAR_CODE;
    private String INSG_DDID;
    private String INSGR_PNID;
    private String WZMC;
    private String KPBH;
    private String RFID_CODE;
    private String BAR_CODE;
    @Generated(hash = 2053977385)
    public INSPECT_GROUP(Long ID, Long INSG_ID, String INSG_KPBH, String INSG_RFID,
            String INSG_BAR_CODE, String INSG_DDID, String INSGR_PNID, String WZMC, String KPBH,
            String RFID_CODE, String BAR_CODE) {
        this.ID = ID;
        this.INSG_ID = INSG_ID;
        this.INSG_KPBH = INSG_KPBH;
        this.INSG_RFID = INSG_RFID;
        this.INSG_BAR_CODE = INSG_BAR_CODE;
        this.INSG_DDID = INSG_DDID;
        this.INSGR_PNID = INSGR_PNID;
        this.WZMC = WZMC;
        this.KPBH = KPBH;
        this.RFID_CODE = RFID_CODE;
        this.BAR_CODE = BAR_CODE;
    }
    @Generated(hash = 492608706)
    public INSPECT_GROUP() {
    }
    public Long getID() {
        return this.ID;
    }
    public void setID(Long ID) {
        this.ID = ID;
    }
    public Long getINSG_ID() {
        return this.INSG_ID;
    }
    public void setINSG_ID(Long INSG_ID) {
        this.INSG_ID = INSG_ID;
    }
    public String getINSG_KPBH() {
        return this.INSG_KPBH;
    }
    public void setINSG_KPBH(String INSG_KPBH) {
        this.INSG_KPBH = INSG_KPBH;
    }
    public String getINSG_RFID() {
        return this.INSG_RFID;
    }
    public void setINSG_RFID(String INSG_RFID) {
        this.INSG_RFID = INSG_RFID;
    }
    public String getINSG_BAR_CODE() {
        return this.INSG_BAR_CODE;
    }
    public void setINSG_BAR_CODE(String INSG_BAR_CODE) {
        this.INSG_BAR_CODE = INSG_BAR_CODE;
    }
    public String getINSG_DDID() {
        return this.INSG_DDID;
    }
    public void setINSG_DDID(String INSG_DDID) {
        this.INSG_DDID = INSG_DDID;
    }
    public String getINSGR_PNID() {
        return this.INSGR_PNID;
    }
    public void setINSGR_PNID(String INSGR_PNID) {
        this.INSGR_PNID = INSGR_PNID;
    }
    public String getWZMC() {
        return this.WZMC;
    }
    public void setWZMC(String WZMC) {
        this.WZMC = WZMC;
    }
    public String getKPBH() {
        return this.KPBH;
    }
    public void setKPBH(String KPBH) {
        this.KPBH = KPBH;
    }
    public String getRFID_CODE() {
        return this.RFID_CODE;
    }
    public void setRFID_CODE(String RFID_CODE) {
        this.RFID_CODE = RFID_CODE;
    }
    public String getBAR_CODE() {
        return this.BAR_CODE;
    }
    public void setBAR_CODE(String BAR_CODE) {
        this.BAR_CODE = BAR_CODE;
    }


}
