package coder.aihui.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;

/**
 * Entity mapped to table INSPECT__REP.
 */
@Entity
public class INSPECT_REP {
    @Id
    @Property(nameInDb = "INSR__ID")
    private Long           INSR_ID;
    private Integer        INSR_FK_ID;         //关联的PLanID
    private String         INSR_TYPE;
    private java.util.Date INSR_EXEC_DATE;
    private java.util.Date INSR_PRIOR_EXEC_DATE;
    private Integer        INSR_USER_ID;
    private String         INSR_RESULT;
    private String         INSR_NID;
    private String         INSR_REMARK;
    private Integer        INSR_WX_NEED;
    private java.util.Date INSR_CREATE_DATE;
    private Integer        INSR_CREATE_USER;
    private java.util.Date INSR_UPDATE_DATE;
    private Integer        INSR_UPDATE_USER;
    private String         KPBH;
    private Long           DDID;
    private String         DDMC;
    private String         WZMC;
    private String         ZQLX;
    private Long           XJFL;
    private String         XJFL_MC;
    private String         INSE_CYCLE;
    private String         RFID_CODE;
    private String         BAR_CODE;
    private java.util.Date SYNC_DATE;
    private Integer        SYNC_FLAG;
    private String         UUID;
    private String         KPBH_OLD;
    private String         REP_NAMES;
    private String         REP_IDS;
    private Long           KSID;
    private String         KSMC;
    private String         SCBH;
    private String         GGXH;
    private String         PPMC;
    private Long           NET_INSPRID;
    private Integer        ISCHECK;
    private String        PDAID;


    private Integer UP_FILE_ID;
    private Integer UP_FILE_TYPE;
    @Generated(hash = 985752119)
    public INSPECT_REP(Long INSR_ID, Integer INSR_FK_ID, String INSR_TYPE,
            java.util.Date INSR_EXEC_DATE, java.util.Date INSR_PRIOR_EXEC_DATE, Integer INSR_USER_ID,
            String INSR_RESULT, String INSR_NID, String INSR_REMARK, Integer INSR_WX_NEED,
            java.util.Date INSR_CREATE_DATE, Integer INSR_CREATE_USER, java.util.Date INSR_UPDATE_DATE,
            Integer INSR_UPDATE_USER, String KPBH, Long DDID, String DDMC, String WZMC, String ZQLX,
            Long XJFL, String XJFL_MC, String INSE_CYCLE, String RFID_CODE, String BAR_CODE,
            java.util.Date SYNC_DATE, Integer SYNC_FLAG, String UUID, String KPBH_OLD, String REP_NAMES,
            String REP_IDS, Long KSID, String KSMC, String SCBH, String GGXH, String PPMC,
            Long NET_INSPRID, Integer ISCHECK, String PDAID, Integer UP_FILE_ID, Integer UP_FILE_TYPE) {
        this.INSR_ID = INSR_ID;
        this.INSR_FK_ID = INSR_FK_ID;
        this.INSR_TYPE = INSR_TYPE;
        this.INSR_EXEC_DATE = INSR_EXEC_DATE;
        this.INSR_PRIOR_EXEC_DATE = INSR_PRIOR_EXEC_DATE;
        this.INSR_USER_ID = INSR_USER_ID;
        this.INSR_RESULT = INSR_RESULT;
        this.INSR_NID = INSR_NID;
        this.INSR_REMARK = INSR_REMARK;
        this.INSR_WX_NEED = INSR_WX_NEED;
        this.INSR_CREATE_DATE = INSR_CREATE_DATE;
        this.INSR_CREATE_USER = INSR_CREATE_USER;
        this.INSR_UPDATE_DATE = INSR_UPDATE_DATE;
        this.INSR_UPDATE_USER = INSR_UPDATE_USER;
        this.KPBH = KPBH;
        this.DDID = DDID;
        this.DDMC = DDMC;
        this.WZMC = WZMC;
        this.ZQLX = ZQLX;
        this.XJFL = XJFL;
        this.XJFL_MC = XJFL_MC;
        this.INSE_CYCLE = INSE_CYCLE;
        this.RFID_CODE = RFID_CODE;
        this.BAR_CODE = BAR_CODE;
        this.SYNC_DATE = SYNC_DATE;
        this.SYNC_FLAG = SYNC_FLAG;
        this.UUID = UUID;
        this.KPBH_OLD = KPBH_OLD;
        this.REP_NAMES = REP_NAMES;
        this.REP_IDS = REP_IDS;
        this.KSID = KSID;
        this.KSMC = KSMC;
        this.SCBH = SCBH;
        this.GGXH = GGXH;
        this.PPMC = PPMC;
        this.NET_INSPRID = NET_INSPRID;
        this.ISCHECK = ISCHECK;
        this.PDAID = PDAID;
        this.UP_FILE_ID = UP_FILE_ID;
        this.UP_FILE_TYPE = UP_FILE_TYPE;
    }
    @Generated(hash = 1183795842)
    public INSPECT_REP() {
    }
    public Long getINSR_ID() {
        return this.INSR_ID;
    }
    public void setINSR_ID(Long INSR_ID) {
        this.INSR_ID = INSR_ID;
    }
    public Integer getINSR_FK_ID() {
        return this.INSR_FK_ID;
    }
    public void setINSR_FK_ID(Integer INSR_FK_ID) {
        this.INSR_FK_ID = INSR_FK_ID;
    }
    public String getINSR_TYPE() {
        return this.INSR_TYPE;
    }
    public void setINSR_TYPE(String INSR_TYPE) {
        this.INSR_TYPE = INSR_TYPE;
    }
    public java.util.Date getINSR_EXEC_DATE() {
        return this.INSR_EXEC_DATE;
    }
    public void setINSR_EXEC_DATE(java.util.Date INSR_EXEC_DATE) {
        this.INSR_EXEC_DATE = INSR_EXEC_DATE;
    }
    public java.util.Date getINSR_PRIOR_EXEC_DATE() {
        return this.INSR_PRIOR_EXEC_DATE;
    }
    public void setINSR_PRIOR_EXEC_DATE(java.util.Date INSR_PRIOR_EXEC_DATE) {
        this.INSR_PRIOR_EXEC_DATE = INSR_PRIOR_EXEC_DATE;
    }
    public Integer getINSR_USER_ID() {
        return this.INSR_USER_ID;
    }
    public void setINSR_USER_ID(Integer INSR_USER_ID) {
        this.INSR_USER_ID = INSR_USER_ID;
    }
    public String getINSR_RESULT() {
        return this.INSR_RESULT;
    }
    public void setINSR_RESULT(String INSR_RESULT) {
        this.INSR_RESULT = INSR_RESULT;
    }
    public String getINSR_NID() {
        return this.INSR_NID;
    }
    public void setINSR_NID(String INSR_NID) {
        this.INSR_NID = INSR_NID;
    }
    public String getINSR_REMARK() {
        return this.INSR_REMARK;
    }
    public void setINSR_REMARK(String INSR_REMARK) {
        this.INSR_REMARK = INSR_REMARK;
    }
    public Integer getINSR_WX_NEED() {
        return this.INSR_WX_NEED;
    }
    public void setINSR_WX_NEED(Integer INSR_WX_NEED) {
        this.INSR_WX_NEED = INSR_WX_NEED;
    }
    public java.util.Date getINSR_CREATE_DATE() {
        return this.INSR_CREATE_DATE;
    }
    public void setINSR_CREATE_DATE(java.util.Date INSR_CREATE_DATE) {
        this.INSR_CREATE_DATE = INSR_CREATE_DATE;
    }
    public Integer getINSR_CREATE_USER() {
        return this.INSR_CREATE_USER;
    }
    public void setINSR_CREATE_USER(Integer INSR_CREATE_USER) {
        this.INSR_CREATE_USER = INSR_CREATE_USER;
    }
    public java.util.Date getINSR_UPDATE_DATE() {
        return this.INSR_UPDATE_DATE;
    }
    public void setINSR_UPDATE_DATE(java.util.Date INSR_UPDATE_DATE) {
        this.INSR_UPDATE_DATE = INSR_UPDATE_DATE;
    }
    public Integer getINSR_UPDATE_USER() {
        return this.INSR_UPDATE_USER;
    }
    public void setINSR_UPDATE_USER(Integer INSR_UPDATE_USER) {
        this.INSR_UPDATE_USER = INSR_UPDATE_USER;
    }
    public String getKPBH() {
        return this.KPBH;
    }
    public void setKPBH(String KPBH) {
        this.KPBH = KPBH;
    }
    public Long getDDID() {
        return this.DDID;
    }
    public void setDDID(Long DDID) {
        this.DDID = DDID;
    }
    public String getDDMC() {
        return this.DDMC;
    }
    public void setDDMC(String DDMC) {
        this.DDMC = DDMC;
    }
    public String getWZMC() {
        return this.WZMC;
    }
    public void setWZMC(String WZMC) {
        this.WZMC = WZMC;
    }
    public String getZQLX() {
        return this.ZQLX;
    }
    public void setZQLX(String ZQLX) {
        this.ZQLX = ZQLX;
    }
    public Long getXJFL() {
        return this.XJFL;
    }
    public void setXJFL(Long XJFL) {
        this.XJFL = XJFL;
    }
    public String getXJFL_MC() {
        return this.XJFL_MC;
    }
    public void setXJFL_MC(String XJFL_MC) {
        this.XJFL_MC = XJFL_MC;
    }
    public String getINSE_CYCLE() {
        return this.INSE_CYCLE;
    }
    public void setINSE_CYCLE(String INSE_CYCLE) {
        this.INSE_CYCLE = INSE_CYCLE;
    }
    public String getRFID_CODE() {
        return this.RFID_CODE;
    }
    public void setRFID_CODE(String RFID_CODE) {
        this.RFID_CODE = RFID_CODE;
    }
    public String getBAR_CODE() {
        return this.BAR_CODE;
    }
    public void setBAR_CODE(String BAR_CODE) {
        this.BAR_CODE = BAR_CODE;
    }
    public java.util.Date getSYNC_DATE() {
        return this.SYNC_DATE;
    }
    public void setSYNC_DATE(java.util.Date SYNC_DATE) {
        this.SYNC_DATE = SYNC_DATE;
    }
    public Integer getSYNC_FLAG() {
        return this.SYNC_FLAG;
    }
    public void setSYNC_FLAG(Integer SYNC_FLAG) {
        this.SYNC_FLAG = SYNC_FLAG;
    }
    public String getUUID() {
        return this.UUID;
    }
    public void setUUID(String UUID) {
        this.UUID = UUID;
    }
    public String getKPBH_OLD() {
        return this.KPBH_OLD;
    }
    public void setKPBH_OLD(String KPBH_OLD) {
        this.KPBH_OLD = KPBH_OLD;
    }
    public String getREP_NAMES() {
        return this.REP_NAMES;
    }
    public void setREP_NAMES(String REP_NAMES) {
        this.REP_NAMES = REP_NAMES;
    }
    public String getREP_IDS() {
        return this.REP_IDS;
    }
    public void setREP_IDS(String REP_IDS) {
        this.REP_IDS = REP_IDS;
    }
    public Long getKSID() {
        return this.KSID;
    }
    public void setKSID(Long KSID) {
        this.KSID = KSID;
    }
    public String getKSMC() {
        return this.KSMC;
    }
    public void setKSMC(String KSMC) {
        this.KSMC = KSMC;
    }
    public String getSCBH() {
        return this.SCBH;
    }
    public void setSCBH(String SCBH) {
        this.SCBH = SCBH;
    }
    public String getGGXH() {
        return this.GGXH;
    }
    public void setGGXH(String GGXH) {
        this.GGXH = GGXH;
    }
    public String getPPMC() {
        return this.PPMC;
    }
    public void setPPMC(String PPMC) {
        this.PPMC = PPMC;
    }
    public Long getNET_INSPRID() {
        return this.NET_INSPRID;
    }
    public void setNET_INSPRID(Long NET_INSPRID) {
        this.NET_INSPRID = NET_INSPRID;
    }
    public Integer getISCHECK() {
        return this.ISCHECK;
    }
    public void setISCHECK(Integer ISCHECK) {
        this.ISCHECK = ISCHECK;
    }
    public Integer getUP_FILE_ID() {
        return this.UP_FILE_ID;
    }
    public void setUP_FILE_ID(Integer UP_FILE_ID) {
        this.UP_FILE_ID = UP_FILE_ID;
    }
    public Integer getUP_FILE_TYPE() {
        return this.UP_FILE_TYPE;
    }
    public void setUP_FILE_TYPE(Integer UP_FILE_TYPE) {
        this.UP_FILE_TYPE = UP_FILE_TYPE;
    }
    public String getPDAID() {
        return this.PDAID;
    }
    public void setPDAID(String PDAID) {
        this.PDAID = PDAID;
    }


}
