package coder.aihui.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;
import org.greenrobot.greendao.annotation.Generated;
import java.util.Date;

/**
 * Entity mapped to table INSPECT_TEMPLET_ITEM.
 */
@Entity
public class InspectTempletItem {
    @Id
    @Property(nameInDb = "ITEM__ID")
    private Long           ITEM_ID;
    private String         PDC_CLASS_ID;
    private String         PDC_CLASS_CODE;
    private String         ITEM_CODE;
    private String         ITEM_CLASS_CODE;
    private String         ITEM_NAME;
    private String         ITEM_REMARK;
    private String         ITEM_PARENT_ID;
    private Integer        ITEM_IS_LASTLEVEL;
    private Integer        ITEM_IS_DEL;
    private java.util.Date ITEM_DEL_DATE;
    private String         ITEM_NAME_PINYIN;
    private String         ITEM_NAME_WUBI;
    private Integer        ITEM_SORT;
    private String         ITEM_GRADE;
    private Integer        ITEM_LEVEL;
    private Integer        ITEM_TYPE;                   //1是巡检 2是Pm
    private Integer        ITEM_CREATE_USER;
    private java.util.Date ITEM_CREATE_DATE;
    private Integer        ITEM_UPDATE_USER;
    private java.util.Date ITEM_UPDATE_DATE;
    private String         ITEM_EXT_STRING1;
    private String         ITEM_EXT_STRING2;
    private String         ITEM_EXT_STRING3;
    private String         ITEM_EXT_STRING4;
    private String         ITEM_EXT_STRING5;
    private String         ITEM_EXT_STRING6;
    private Double         ITEM_EXT_NUM1;
    private Double         ITEM_EXT_NUM3;
    private Double         ITEM_EXT_NUM2;
    private java.util.Date ITEM_EXT_DATE1;
    private java.util.Date ITEM_EXT_DATE2;
    private java.util.Date ITEM_EXT_DATE3;
    private String         ITEM_KFID;
    private Integer        ITEM_IS_SYSTEM;
    @Generated(hash = 58421088)
    public InspectTempletItem(Long ITEM_ID, String PDC_CLASS_ID, String PDC_CLASS_CODE,
            String ITEM_CODE, String ITEM_CLASS_CODE, String ITEM_NAME, String ITEM_REMARK,
            String ITEM_PARENT_ID, Integer ITEM_IS_LASTLEVEL, Integer ITEM_IS_DEL,
            java.util.Date ITEM_DEL_DATE, String ITEM_NAME_PINYIN, String ITEM_NAME_WUBI,
            Integer ITEM_SORT, String ITEM_GRADE, Integer ITEM_LEVEL, Integer ITEM_TYPE,
            Integer ITEM_CREATE_USER, java.util.Date ITEM_CREATE_DATE, Integer ITEM_UPDATE_USER,
            java.util.Date ITEM_UPDATE_DATE, String ITEM_EXT_STRING1, String ITEM_EXT_STRING2,
            String ITEM_EXT_STRING3, String ITEM_EXT_STRING4, String ITEM_EXT_STRING5,
            String ITEM_EXT_STRING6, Double ITEM_EXT_NUM1, Double ITEM_EXT_NUM3, Double ITEM_EXT_NUM2,
            java.util.Date ITEM_EXT_DATE1, java.util.Date ITEM_EXT_DATE2, java.util.Date ITEM_EXT_DATE3,
            String ITEM_KFID, Integer ITEM_IS_SYSTEM) {
        this.ITEM_ID = ITEM_ID;
        this.PDC_CLASS_ID = PDC_CLASS_ID;
        this.PDC_CLASS_CODE = PDC_CLASS_CODE;
        this.ITEM_CODE = ITEM_CODE;
        this.ITEM_CLASS_CODE = ITEM_CLASS_CODE;
        this.ITEM_NAME = ITEM_NAME;
        this.ITEM_REMARK = ITEM_REMARK;
        this.ITEM_PARENT_ID = ITEM_PARENT_ID;
        this.ITEM_IS_LASTLEVEL = ITEM_IS_LASTLEVEL;
        this.ITEM_IS_DEL = ITEM_IS_DEL;
        this.ITEM_DEL_DATE = ITEM_DEL_DATE;
        this.ITEM_NAME_PINYIN = ITEM_NAME_PINYIN;
        this.ITEM_NAME_WUBI = ITEM_NAME_WUBI;
        this.ITEM_SORT = ITEM_SORT;
        this.ITEM_GRADE = ITEM_GRADE;
        this.ITEM_LEVEL = ITEM_LEVEL;
        this.ITEM_TYPE = ITEM_TYPE;
        this.ITEM_CREATE_USER = ITEM_CREATE_USER;
        this.ITEM_CREATE_DATE = ITEM_CREATE_DATE;
        this.ITEM_UPDATE_USER = ITEM_UPDATE_USER;
        this.ITEM_UPDATE_DATE = ITEM_UPDATE_DATE;
        this.ITEM_EXT_STRING1 = ITEM_EXT_STRING1;
        this.ITEM_EXT_STRING2 = ITEM_EXT_STRING2;
        this.ITEM_EXT_STRING3 = ITEM_EXT_STRING3;
        this.ITEM_EXT_STRING4 = ITEM_EXT_STRING4;
        this.ITEM_EXT_STRING5 = ITEM_EXT_STRING5;
        this.ITEM_EXT_STRING6 = ITEM_EXT_STRING6;
        this.ITEM_EXT_NUM1 = ITEM_EXT_NUM1;
        this.ITEM_EXT_NUM3 = ITEM_EXT_NUM3;
        this.ITEM_EXT_NUM2 = ITEM_EXT_NUM2;
        this.ITEM_EXT_DATE1 = ITEM_EXT_DATE1;
        this.ITEM_EXT_DATE2 = ITEM_EXT_DATE2;
        this.ITEM_EXT_DATE3 = ITEM_EXT_DATE3;
        this.ITEM_KFID = ITEM_KFID;
        this.ITEM_IS_SYSTEM = ITEM_IS_SYSTEM;
    }
    @Generated(hash = 1310190390)
    public InspectTempletItem() {
    }
    public Long getITEM_ID() {
        return this.ITEM_ID;
    }
    public void setITEM_ID(Long ITEM_ID) {
        this.ITEM_ID = ITEM_ID;
    }
    public String getPDC_CLASS_ID() {
        return this.PDC_CLASS_ID;
    }
    public void setPDC_CLASS_ID(String PDC_CLASS_ID) {
        this.PDC_CLASS_ID = PDC_CLASS_ID;
    }
    public String getPDC_CLASS_CODE() {
        return this.PDC_CLASS_CODE;
    }
    public void setPDC_CLASS_CODE(String PDC_CLASS_CODE) {
        this.PDC_CLASS_CODE = PDC_CLASS_CODE;
    }
    public String getITEM_CODE() {
        return this.ITEM_CODE;
    }
    public void setITEM_CODE(String ITEM_CODE) {
        this.ITEM_CODE = ITEM_CODE;
    }
    public String getITEM_CLASS_CODE() {
        return this.ITEM_CLASS_CODE;
    }
    public void setITEM_CLASS_CODE(String ITEM_CLASS_CODE) {
        this.ITEM_CLASS_CODE = ITEM_CLASS_CODE;
    }
    public String getITEM_NAME() {
        return this.ITEM_NAME;
    }
    public void setITEM_NAME(String ITEM_NAME) {
        this.ITEM_NAME = ITEM_NAME;
    }
    public String getITEM_REMARK() {
        return this.ITEM_REMARK;
    }
    public void setITEM_REMARK(String ITEM_REMARK) {
        this.ITEM_REMARK = ITEM_REMARK;
    }
    public String getITEM_PARENT_ID() {
        return this.ITEM_PARENT_ID;
    }
    public void setITEM_PARENT_ID(String ITEM_PARENT_ID) {
        this.ITEM_PARENT_ID = ITEM_PARENT_ID;
    }
    public Integer getITEM_IS_LASTLEVEL() {
        return this.ITEM_IS_LASTLEVEL;
    }
    public void setITEM_IS_LASTLEVEL(Integer ITEM_IS_LASTLEVEL) {
        this.ITEM_IS_LASTLEVEL = ITEM_IS_LASTLEVEL;
    }
    public Integer getITEM_IS_DEL() {
        return this.ITEM_IS_DEL;
    }
    public void setITEM_IS_DEL(Integer ITEM_IS_DEL) {
        this.ITEM_IS_DEL = ITEM_IS_DEL;
    }
    public java.util.Date getITEM_DEL_DATE() {
        return this.ITEM_DEL_DATE;
    }
    public void setITEM_DEL_DATE(java.util.Date ITEM_DEL_DATE) {
        this.ITEM_DEL_DATE = ITEM_DEL_DATE;
    }
    public String getITEM_NAME_PINYIN() {
        return this.ITEM_NAME_PINYIN;
    }
    public void setITEM_NAME_PINYIN(String ITEM_NAME_PINYIN) {
        this.ITEM_NAME_PINYIN = ITEM_NAME_PINYIN;
    }
    public String getITEM_NAME_WUBI() {
        return this.ITEM_NAME_WUBI;
    }
    public void setITEM_NAME_WUBI(String ITEM_NAME_WUBI) {
        this.ITEM_NAME_WUBI = ITEM_NAME_WUBI;
    }
    public Integer getITEM_SORT() {
        return this.ITEM_SORT;
    }
    public void setITEM_SORT(Integer ITEM_SORT) {
        this.ITEM_SORT = ITEM_SORT;
    }
    public String getITEM_GRADE() {
        return this.ITEM_GRADE;
    }
    public void setITEM_GRADE(String ITEM_GRADE) {
        this.ITEM_GRADE = ITEM_GRADE;
    }
    public Integer getITEM_LEVEL() {
        return this.ITEM_LEVEL;
    }
    public void setITEM_LEVEL(Integer ITEM_LEVEL) {
        this.ITEM_LEVEL = ITEM_LEVEL;
    }
    public Integer getITEM_TYPE() {
        return this.ITEM_TYPE;
    }
    public void setITEM_TYPE(Integer ITEM_TYPE) {
        this.ITEM_TYPE = ITEM_TYPE;
    }
    public Integer getITEM_CREATE_USER() {
        return this.ITEM_CREATE_USER;
    }
    public void setITEM_CREATE_USER(Integer ITEM_CREATE_USER) {
        this.ITEM_CREATE_USER = ITEM_CREATE_USER;
    }
    public java.util.Date getITEM_CREATE_DATE() {
        return this.ITEM_CREATE_DATE;
    }
    public void setITEM_CREATE_DATE(java.util.Date ITEM_CREATE_DATE) {
        this.ITEM_CREATE_DATE = ITEM_CREATE_DATE;
    }
    public Integer getITEM_UPDATE_USER() {
        return this.ITEM_UPDATE_USER;
    }
    public void setITEM_UPDATE_USER(Integer ITEM_UPDATE_USER) {
        this.ITEM_UPDATE_USER = ITEM_UPDATE_USER;
    }
    public java.util.Date getITEM_UPDATE_DATE() {
        return this.ITEM_UPDATE_DATE;
    }
    public void setITEM_UPDATE_DATE(java.util.Date ITEM_UPDATE_DATE) {
        this.ITEM_UPDATE_DATE = ITEM_UPDATE_DATE;
    }
    public String getITEM_EXT_STRING1() {
        return this.ITEM_EXT_STRING1;
    }
    public void setITEM_EXT_STRING1(String ITEM_EXT_STRING1) {
        this.ITEM_EXT_STRING1 = ITEM_EXT_STRING1;
    }
    public String getITEM_EXT_STRING2() {
        return this.ITEM_EXT_STRING2;
    }
    public void setITEM_EXT_STRING2(String ITEM_EXT_STRING2) {
        this.ITEM_EXT_STRING2 = ITEM_EXT_STRING2;
    }
    public String getITEM_EXT_STRING3() {
        return this.ITEM_EXT_STRING3;
    }
    public void setITEM_EXT_STRING3(String ITEM_EXT_STRING3) {
        this.ITEM_EXT_STRING3 = ITEM_EXT_STRING3;
    }
    public String getITEM_EXT_STRING4() {
        return this.ITEM_EXT_STRING4;
    }
    public void setITEM_EXT_STRING4(String ITEM_EXT_STRING4) {
        this.ITEM_EXT_STRING4 = ITEM_EXT_STRING4;
    }
    public String getITEM_EXT_STRING5() {
        return this.ITEM_EXT_STRING5;
    }
    public void setITEM_EXT_STRING5(String ITEM_EXT_STRING5) {
        this.ITEM_EXT_STRING5 = ITEM_EXT_STRING5;
    }
    public String getITEM_EXT_STRING6() {
        return this.ITEM_EXT_STRING6;
    }
    public void setITEM_EXT_STRING6(String ITEM_EXT_STRING6) {
        this.ITEM_EXT_STRING6 = ITEM_EXT_STRING6;
    }
    public Double getITEM_EXT_NUM1() {
        return this.ITEM_EXT_NUM1;
    }
    public void setITEM_EXT_NUM1(Double ITEM_EXT_NUM1) {
        this.ITEM_EXT_NUM1 = ITEM_EXT_NUM1;
    }
    public Double getITEM_EXT_NUM3() {
        return this.ITEM_EXT_NUM3;
    }
    public void setITEM_EXT_NUM3(Double ITEM_EXT_NUM3) {
        this.ITEM_EXT_NUM3 = ITEM_EXT_NUM3;
    }
    public Double getITEM_EXT_NUM2() {
        return this.ITEM_EXT_NUM2;
    }
    public void setITEM_EXT_NUM2(Double ITEM_EXT_NUM2) {
        this.ITEM_EXT_NUM2 = ITEM_EXT_NUM2;
    }
    public java.util.Date getITEM_EXT_DATE1() {
        return this.ITEM_EXT_DATE1;
    }
    public void setITEM_EXT_DATE1(java.util.Date ITEM_EXT_DATE1) {
        this.ITEM_EXT_DATE1 = ITEM_EXT_DATE1;
    }
    public java.util.Date getITEM_EXT_DATE2() {
        return this.ITEM_EXT_DATE2;
    }
    public void setITEM_EXT_DATE2(java.util.Date ITEM_EXT_DATE2) {
        this.ITEM_EXT_DATE2 = ITEM_EXT_DATE2;
    }
    public java.util.Date getITEM_EXT_DATE3() {
        return this.ITEM_EXT_DATE3;
    }
    public void setITEM_EXT_DATE3(java.util.Date ITEM_EXT_DATE3) {
        this.ITEM_EXT_DATE3 = ITEM_EXT_DATE3;
    }
    public String getITEM_KFID() {
        return this.ITEM_KFID;
    }
    public void setITEM_KFID(String ITEM_KFID) {
        this.ITEM_KFID = ITEM_KFID;
    }
    public Integer getITEM_IS_SYSTEM() {
        return this.ITEM_IS_SYSTEM;
    }
    public void setITEM_IS_SYSTEM(Integer ITEM_IS_SYSTEM) {
        this.ITEM_IS_SYSTEM = ITEM_IS_SYSTEM;
    }


}
