package coder.aihui.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;
import org.greenrobot.greendao.annotation.Generated;
import java.util.Date;

/**
 * Entity mapped to table INSPECT__REP__PIC.
 */
@Entity
public class INSPECT_REP_PIC extends MyEntity {

    @Id
    @Property(nameInDb = "INSPP__ID")
    private Long INSPP_ID;
    private Long INSPR_REP_ID;
    private String PUUID;
    private String UUID;
    private String URL;
    private java.util.Date SYNC_DATE;
    private Integer SYNC_FLAG;
    private String SMALL_URL;
    private Integer UP_FILE_ID;
    private Integer UP_FILE_TYPE;
    @Generated(hash = 2033574683)
    public INSPECT_REP_PIC(Long INSPP_ID, Long INSPR_REP_ID, String PUUID, String UUID, String URL,
            java.util.Date SYNC_DATE, Integer SYNC_FLAG, String SMALL_URL, Integer UP_FILE_ID,
            Integer UP_FILE_TYPE) {
        this.INSPP_ID = INSPP_ID;
        this.INSPR_REP_ID = INSPR_REP_ID;
        this.PUUID = PUUID;
        this.UUID = UUID;
        this.URL = URL;
        this.SYNC_DATE = SYNC_DATE;
        this.SYNC_FLAG = SYNC_FLAG;
        this.SMALL_URL = SMALL_URL;
        this.UP_FILE_ID = UP_FILE_ID;
        this.UP_FILE_TYPE = UP_FILE_TYPE;
    }
    @Generated(hash = 1530057764)
    public INSPECT_REP_PIC() {
    }
    public Long getINSPP_ID() {
        return this.INSPP_ID;
    }
    public void setINSPP_ID(Long INSPP_ID) {
        this.INSPP_ID = INSPP_ID;
    }
    public Long getINSPR_REP_ID() {
        return this.INSPR_REP_ID;
    }
    public void setINSPR_REP_ID(Long INSPR_REP_ID) {
        this.INSPR_REP_ID = INSPR_REP_ID;
    }
    public String getPUUID() {
        return this.PUUID;
    }
    public void setPUUID(String PUUID) {
        this.PUUID = PUUID;
    }
    public String getUUID() {
        return this.UUID;
    }
    public void setUUID(String UUID) {
        this.UUID = UUID;
    }
    public String getURL() {
        return this.URL;
    }
    public void setURL(String URL) {
        this.URL = URL;
    }
    public java.util.Date getSYNC_DATE() {
        return this.SYNC_DATE;
    }
    public void setSYNC_DATE(java.util.Date SYNC_DATE) {
        this.SYNC_DATE = SYNC_DATE;
    }
    public Integer getSYNC_FLAG() {
        return this.SYNC_FLAG;
    }
    public void setSYNC_FLAG(Integer SYNC_FLAG) {
        this.SYNC_FLAG = SYNC_FLAG;
    }
    public String getSMALL_URL() {
        return this.SMALL_URL;
    }
    public void setSMALL_URL(String SMALL_URL) {
        this.SMALL_URL = SMALL_URL;
    }
    public Integer getUP_FILE_ID() {
        return this.UP_FILE_ID;
    }
    public void setUP_FILE_ID(Integer UP_FILE_ID) {
        this.UP_FILE_ID = UP_FILE_ID;
    }
    public Integer getUP_FILE_TYPE() {
        return this.UP_FILE_TYPE;
    }
    public void setUP_FILE_TYPE(Integer UP_FILE_TYPE) {
        this.UP_FILE_TYPE = UP_FILE_TYPE;
    }



}
