package coder.aihui.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;

/**
 * Entity mapped to table PDA__ASSET__CHECK.
 */


@Entity

public class PDA_ASSET_CHECK {
    @Id
    @Property(nameInDb = "CHECK__ID")
    private Long CHECK_ID;
    private Long ASSET_ID;
    private String QCPC;
    private String PDA_ID;
    private String CHECK_TYPE;
    private String DS_TYPE;
    private Integer IS_CHANGE;
    private String CHANGE_DEPT;
    private Integer IS_CHANGE_DD;
    private String CHANGE_DDID;
    private String ASSET_CHECK_ID;
    private String ASSET_CHECK_NAME;
    private java.util.Date ASSET_CHECK_DATE;
    private String ASSET_CHECKER_ID;
    private String ASSET_CHECKER_NAME;
    private java.util.Date ASSET_CHECKER_DATE;
    private String ASSET_COLLATE_ID;
    private String ASSET_COLLATE_NAME;
    private java.util.Date ASSET_COLLATE_DATE;
    private Integer BGRID;
    private String BGRXM;
    private Integer ASSET_SYNC_FLAG;
    private java.util.Date ASSET_SYNC_DATE;
    private String REMARKS;
    private String DDID;
    private String KSID;
    private String DQDDID;
    private String DQKSID;
    private String DQDDMC;//当前位置名称，显示需要，不再去查一次
    private String UUID;
    private String LABEL_DEFAULT_NAME;
    private String        PDAID;

    @Generated(hash = 1641979191)
    public PDA_ASSET_CHECK(Long CHECK_ID, Long ASSET_ID, String QCPC, String PDA_ID, String CHECK_TYPE,
            String DS_TYPE, Integer IS_CHANGE, String CHANGE_DEPT, Integer IS_CHANGE_DD,
            String CHANGE_DDID, String ASSET_CHECK_ID, String ASSET_CHECK_NAME,
            java.util.Date ASSET_CHECK_DATE, String ASSET_CHECKER_ID, String ASSET_CHECKER_NAME,
            java.util.Date ASSET_CHECKER_DATE, String ASSET_COLLATE_ID, String ASSET_COLLATE_NAME,
            java.util.Date ASSET_COLLATE_DATE, Integer BGRID, String BGRXM, Integer ASSET_SYNC_FLAG,
            java.util.Date ASSET_SYNC_DATE, String REMARKS, String DDID, String KSID, String DQDDID,
            String DQKSID, String DQDDMC, String UUID, String LABEL_DEFAULT_NAME, String PDAID) {
        this.CHECK_ID = CHECK_ID;
        this.ASSET_ID = ASSET_ID;
        this.QCPC = QCPC;
        this.PDA_ID = PDA_ID;
        this.CHECK_TYPE = CHECK_TYPE;
        this.DS_TYPE = DS_TYPE;
        this.IS_CHANGE = IS_CHANGE;
        this.CHANGE_DEPT = CHANGE_DEPT;
        this.IS_CHANGE_DD = IS_CHANGE_DD;
        this.CHANGE_DDID = CHANGE_DDID;
        this.ASSET_CHECK_ID = ASSET_CHECK_ID;
        this.ASSET_CHECK_NAME = ASSET_CHECK_NAME;
        this.ASSET_CHECK_DATE = ASSET_CHECK_DATE;
        this.ASSET_CHECKER_ID = ASSET_CHECKER_ID;
        this.ASSET_CHECKER_NAME = ASSET_CHECKER_NAME;
        this.ASSET_CHECKER_DATE = ASSET_CHECKER_DATE;
        this.ASSET_COLLATE_ID = ASSET_COLLATE_ID;
        this.ASSET_COLLATE_NAME = ASSET_COLLATE_NAME;
        this.ASSET_COLLATE_DATE = ASSET_COLLATE_DATE;
        this.BGRID = BGRID;
        this.BGRXM = BGRXM;
        this.ASSET_SYNC_FLAG = ASSET_SYNC_FLAG;
        this.ASSET_SYNC_DATE = ASSET_SYNC_DATE;
        this.REMARKS = REMARKS;
        this.DDID = DDID;
        this.KSID = KSID;
        this.DQDDID = DQDDID;
        this.DQKSID = DQKSID;
        this.DQDDMC = DQDDMC;
        this.UUID = UUID;
        this.LABEL_DEFAULT_NAME = LABEL_DEFAULT_NAME;
        this.PDAID = PDAID;
    }
    @Generated(hash = 116701339)
    public PDA_ASSET_CHECK() {
    }
    public Long getCHECK_ID() {
        return this.CHECK_ID;
    }
    public void setCHECK_ID(Long CHECK_ID) {
        this.CHECK_ID = CHECK_ID;
    }
    public Long getASSET_ID() {
        return this.ASSET_ID;
    }
    public void setASSET_ID(Long ASSET_ID) {
        this.ASSET_ID = ASSET_ID;
    }
    public String getQCPC() {
        return this.QCPC;
    }
    public void setQCPC(String QCPC) {
        this.QCPC = QCPC;
    }
    public String getPDA_ID() {
        return this.PDA_ID;
    }
    public void setPDA_ID(String PDA_ID) {
        this.PDA_ID = PDA_ID;
    }
    public String getCHECK_TYPE() {
        return this.CHECK_TYPE;
    }
    public void setCHECK_TYPE(String CHECK_TYPE) {
        this.CHECK_TYPE = CHECK_TYPE;
    }
    public String getDS_TYPE() {
        return this.DS_TYPE;
    }
    public void setDS_TYPE(String DS_TYPE) {
        this.DS_TYPE = DS_TYPE;
    }
    public Integer getIS_CHANGE() {
        return this.IS_CHANGE;
    }
    public void setIS_CHANGE(Integer IS_CHANGE) {
        this.IS_CHANGE = IS_CHANGE;
    }
    public String getCHANGE_DEPT() {
        return this.CHANGE_DEPT;
    }
    public void setCHANGE_DEPT(String CHANGE_DEPT) {
        this.CHANGE_DEPT = CHANGE_DEPT;
    }
    public Integer getIS_CHANGE_DD() {
        return this.IS_CHANGE_DD;
    }
    public void setIS_CHANGE_DD(Integer IS_CHANGE_DD) {
        this.IS_CHANGE_DD = IS_CHANGE_DD;
    }
    public String getCHANGE_DDID() {
        return this.CHANGE_DDID;
    }
    public void setCHANGE_DDID(String CHANGE_DDID) {
        this.CHANGE_DDID = CHANGE_DDID;
    }
    public String getASSET_CHECK_ID() {
        return this.ASSET_CHECK_ID;
    }
    public void setASSET_CHECK_ID(String ASSET_CHECK_ID) {
        this.ASSET_CHECK_ID = ASSET_CHECK_ID;
    }
    public String getASSET_CHECK_NAME() {
        return this.ASSET_CHECK_NAME;
    }
    public void setASSET_CHECK_NAME(String ASSET_CHECK_NAME) {
        this.ASSET_CHECK_NAME = ASSET_CHECK_NAME;
    }
    public java.util.Date getASSET_CHECK_DATE() {
        return this.ASSET_CHECK_DATE;
    }
    public void setASSET_CHECK_DATE(java.util.Date ASSET_CHECK_DATE) {
        this.ASSET_CHECK_DATE = ASSET_CHECK_DATE;
    }
    public String getASSET_CHECKER_ID() {
        return this.ASSET_CHECKER_ID;
    }
    public void setASSET_CHECKER_ID(String ASSET_CHECKER_ID) {
        this.ASSET_CHECKER_ID = ASSET_CHECKER_ID;
    }
    public String getASSET_CHECKER_NAME() {
        return this.ASSET_CHECKER_NAME;
    }
    public void setASSET_CHECKER_NAME(String ASSET_CHECKER_NAME) {
        this.ASSET_CHECKER_NAME = ASSET_CHECKER_NAME;
    }
    public java.util.Date getASSET_CHECKER_DATE() {
        return this.ASSET_CHECKER_DATE;
    }
    public void setASSET_CHECKER_DATE(java.util.Date ASSET_CHECKER_DATE) {
        this.ASSET_CHECKER_DATE = ASSET_CHECKER_DATE;
    }
    public String getASSET_COLLATE_ID() {
        return this.ASSET_COLLATE_ID;
    }
    public void setASSET_COLLATE_ID(String ASSET_COLLATE_ID) {
        this.ASSET_COLLATE_ID = ASSET_COLLATE_ID;
    }
    public String getASSET_COLLATE_NAME() {
        return this.ASSET_COLLATE_NAME;
    }
    public void setASSET_COLLATE_NAME(String ASSET_COLLATE_NAME) {
        this.ASSET_COLLATE_NAME = ASSET_COLLATE_NAME;
    }
    public java.util.Date getASSET_COLLATE_DATE() {
        return this.ASSET_COLLATE_DATE;
    }
    public void setASSET_COLLATE_DATE(java.util.Date ASSET_COLLATE_DATE) {
        this.ASSET_COLLATE_DATE = ASSET_COLLATE_DATE;
    }
    public Integer getBGRID() {
        return this.BGRID;
    }
    public void setBGRID(Integer BGRID) {
        this.BGRID = BGRID;
    }
    public String getBGRXM() {
        return this.BGRXM;
    }
    public void setBGRXM(String BGRXM) {
        this.BGRXM = BGRXM;
    }
    public Integer getASSET_SYNC_FLAG() {
        return this.ASSET_SYNC_FLAG;
    }
    public void setASSET_SYNC_FLAG(Integer ASSET_SYNC_FLAG) {
        this.ASSET_SYNC_FLAG = ASSET_SYNC_FLAG;
    }
    public java.util.Date getASSET_SYNC_DATE() {
        return this.ASSET_SYNC_DATE;
    }
    public void setASSET_SYNC_DATE(java.util.Date ASSET_SYNC_DATE) {
        this.ASSET_SYNC_DATE = ASSET_SYNC_DATE;
    }
    public String getREMARKS() {
        return this.REMARKS;
    }
    public void setREMARKS(String REMARKS) {
        this.REMARKS = REMARKS;
    }
    public String getDDID() {
        return this.DDID;
    }
    public void setDDID(String DDID) {
        this.DDID = DDID;
    }
    public String getKSID() {
        return this.KSID;
    }
    public void setKSID(String KSID) {
        this.KSID = KSID;
    }
    public String getDQDDID() {
        return this.DQDDID;
    }
    public void setDQDDID(String DQDDID) {
        this.DQDDID = DQDDID;
    }
    public String getDQKSID() {
        return this.DQKSID;
    }
    public void setDQKSID(String DQKSID) {
        this.DQKSID = DQKSID;
    }
    public String getDQDDMC() {
        return this.DQDDMC;
    }
    public void setDQDDMC(String DQDDMC) {
        this.DQDDMC = DQDDMC;
    }
    public String getUUID() {
        return this.UUID;
    }
    public void setUUID(String UUID) {
        this.UUID = UUID;
    }
    public String getLABEL_DEFAULT_NAME() {
        return this.LABEL_DEFAULT_NAME;
    }
    public void setLABEL_DEFAULT_NAME(String LABEL_DEFAULT_NAME) {
        this.LABEL_DEFAULT_NAME = LABEL_DEFAULT_NAME;
    }
    public String getPDAID() {
        return this.PDAID;
    }
    public void setPDAID(String PDAID) {
        this.PDAID = PDAID;
    }


}
