package coder.aihui.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.mcxtzhang.indexlib.IndexBar.bean.BaseIndexPinyinBean;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table PUB__COMPANY.
 */
@Entity
public class PUB_COMPANY extends BaseIndexPinyinBean {
   // [{"DM":"","IS_BXDW":1,"KFID":"1","LX":"2","ID":1960,"MC":"奥尔良"}]       LX : 1是供应商 2是厂商 3是保修单位
    private Long DM;
    private Integer IS_BXDW;
    private Long KFID;
    private Integer LX;
    @Id
    private Long ID;
    private String MC;
    private Integer NEW_FLAG;
   @Generated(hash = 143605250)
   public PUB_COMPANY(Long DM, Integer IS_BXDW, Long KFID, Integer LX, Long ID, String MC,
           Integer NEW_FLAG) {
       this.DM = DM;
       this.IS_BXDW = IS_BXDW;
       this.KFID = KFID;
       this.LX = LX;
       this.ID = ID;
       this.MC = MC;
       this.NEW_FLAG = NEW_FLAG;
   }
   @Generated(hash = 1026151989)
   public PUB_COMPANY() {
   }

    @Override
    public String getTarget() {
        return MC;
    }

    public Long getDM() {
       return this.DM;
   }
   public void setDM(Long DM) {
       this.DM = DM;
   }
   public Integer getIS_BXDW() {
       return this.IS_BXDW;
   }
   public void setIS_BXDW(Integer IS_BXDW) {
       this.IS_BXDW = IS_BXDW;
   }
   public Long getKFID() {
       return this.KFID;
   }
   public void setKFID(Long KFID) {
       this.KFID = KFID;
   }
   public Integer getLX() {
       return this.LX;
   }
   public void setLX(Integer LX) {
       this.LX = LX;
   }
   public Long getID() {
       return this.ID;
   }
   public void setID(Long ID) {
       this.ID = ID;
   }
   public String getMC() {
       return this.MC;
   }
   public void setMC(String MC) {
       this.MC = MC;
   }
   public Integer getNEW_FLAG() {
       return this.NEW_FLAG;
   }
   public void setNEW_FLAG(Integer NEW_FLAG) {
       this.NEW_FLAG = NEW_FLAG;
   }



}
