package coder.aihui.data.bean;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;

import java.util.Date;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table PUB__DICTIONARY__ITEM.
 */

@Entity
public class PUB_DICTIONARY_ITEM extends MyEntity{
    @Id
    @Property(nameInDb = "ITEM__ID")
    private Long ITEM_ID;
    private String BZ1;
    private String BZ2;
    private Date MODIFY_DATETIME;
    private Date DELETE_DATETIME;
    private Date SYNC_DATETIME;
    private String INPUT_CODE1;
    private Integer SYNC_FLAG;
    private Integer SYS_FLAG;
    private Integer STORE_ID;
    private String DICT_TYPE;
    private String ITEM_EXT_STRING1;
    private String ITEM_EXT_STRING2;
    private String ITEM_NAME;
    private String INPUT_CODE3;
    private String INPUT_CODE2;
    private Integer LEVELS;
    private String ITEM_CODE;
    private Integer LOCK_FLAG;
    private Integer DELETE_FLAG;
    private Integer END_FLAG;
    private Long PARENT_ID;
    private String DICT_ID;
    private Integer ITEM_SORT;
    private String ITEM_EXT_STRING4;
    private String ITEM_EXT_STRING5;
    private String ITEM_EXT_STRING6;
    private Integer ITEM_EXT_NUM1;
    private Integer ITEM_EXT_NUM2;
    private Integer ITEM_EXT_NUM3;
    private String ITEM_EXT_STRING3;
    private String BAR_CODE;
    private Date CREATE_DATE;
    private Date MODIFY_DATE;
    @Generated(hash = 512813908)
    public PUB_DICTIONARY_ITEM(Long ITEM_ID, String BZ1, String BZ2, Date MODIFY_DATETIME,
            Date DELETE_DATETIME, Date SYNC_DATETIME, String INPUT_CODE1, Integer SYNC_FLAG,
            Integer SYS_FLAG, Integer STORE_ID, String DICT_TYPE, String ITEM_EXT_STRING1,
            String ITEM_EXT_STRING2, String ITEM_NAME, String INPUT_CODE3, String INPUT_CODE2,
            Integer LEVELS, String ITEM_CODE, Integer LOCK_FLAG, Integer DELETE_FLAG, Integer END_FLAG,
            Long PARENT_ID, String DICT_ID, Integer ITEM_SORT, String ITEM_EXT_STRING4,
            String ITEM_EXT_STRING5, String ITEM_EXT_STRING6, Integer ITEM_EXT_NUM1,
            Integer ITEM_EXT_NUM2, Integer ITEM_EXT_NUM3, String ITEM_EXT_STRING3, String BAR_CODE,
            Date CREATE_DATE, Date MODIFY_DATE) {
        this.ITEM_ID = ITEM_ID;
        this.BZ1 = BZ1;
        this.BZ2 = BZ2;
        this.MODIFY_DATETIME = MODIFY_DATETIME;
        this.DELETE_DATETIME = DELETE_DATETIME;
        this.SYNC_DATETIME = SYNC_DATETIME;
        this.INPUT_CODE1 = INPUT_CODE1;
        this.SYNC_FLAG = SYNC_FLAG;
        this.SYS_FLAG = SYS_FLAG;
        this.STORE_ID = STORE_ID;
        this.DICT_TYPE = DICT_TYPE;
        this.ITEM_EXT_STRING1 = ITEM_EXT_STRING1;
        this.ITEM_EXT_STRING2 = ITEM_EXT_STRING2;
        this.ITEM_NAME = ITEM_NAME;
        this.INPUT_CODE3 = INPUT_CODE3;
        this.INPUT_CODE2 = INPUT_CODE2;
        this.LEVELS = LEVELS;
        this.ITEM_CODE = ITEM_CODE;
        this.LOCK_FLAG = LOCK_FLAG;
        this.DELETE_FLAG = DELETE_FLAG;
        this.END_FLAG = END_FLAG;
        this.PARENT_ID = PARENT_ID;
        this.DICT_ID = DICT_ID;
        this.ITEM_SORT = ITEM_SORT;
        this.ITEM_EXT_STRING4 = ITEM_EXT_STRING4;
        this.ITEM_EXT_STRING5 = ITEM_EXT_STRING5;
        this.ITEM_EXT_STRING6 = ITEM_EXT_STRING6;
        this.ITEM_EXT_NUM1 = ITEM_EXT_NUM1;
        this.ITEM_EXT_NUM2 = ITEM_EXT_NUM2;
        this.ITEM_EXT_NUM3 = ITEM_EXT_NUM3;
        this.ITEM_EXT_STRING3 = ITEM_EXT_STRING3;
        this.BAR_CODE = BAR_CODE;
        this.CREATE_DATE = CREATE_DATE;
        this.MODIFY_DATE = MODIFY_DATE;
    }
    @Generated(hash = 1792082577)
    public PUB_DICTIONARY_ITEM() {
    }
    public Long getITEM_ID() {
        return this.ITEM_ID;
    }
    public void setITEM_ID(Long ITEM_ID) {
        this.ITEM_ID = ITEM_ID;
    }
    public String getBZ1() {
        return this.BZ1;
    }
    public void setBZ1(String BZ1) {
        this.BZ1 = BZ1;
    }
    public String getBZ2() {
        return this.BZ2;
    }
    public void setBZ2(String BZ2) {
        this.BZ2 = BZ2;
    }
    public Date getMODIFY_DATETIME() {
        return this.MODIFY_DATETIME;
    }
    public void setMODIFY_DATETIME(Date MODIFY_DATETIME) {
        this.MODIFY_DATETIME = MODIFY_DATETIME;
    }
    public Date getDELETE_DATETIME() {
        return this.DELETE_DATETIME;
    }
    public void setDELETE_DATETIME(Date DELETE_DATETIME) {
        this.DELETE_DATETIME = DELETE_DATETIME;
    }
    public Date getSYNC_DATETIME() {
        return this.SYNC_DATETIME;
    }
    public void setSYNC_DATETIME(Date SYNC_DATETIME) {
        this.SYNC_DATETIME = SYNC_DATETIME;
    }
    public String getINPUT_CODE1() {
        return this.INPUT_CODE1;
    }
    public void setINPUT_CODE1(String INPUT_CODE1) {
        this.INPUT_CODE1 = INPUT_CODE1;
    }
    public Integer getSYNC_FLAG() {
        return this.SYNC_FLAG;
    }
    public void setSYNC_FLAG(Integer SYNC_FLAG) {
        this.SYNC_FLAG = SYNC_FLAG;
    }
    public Integer getSYS_FLAG() {
        return this.SYS_FLAG;
    }
    public void setSYS_FLAG(Integer SYS_FLAG) {
        this.SYS_FLAG = SYS_FLAG;
    }
    public Integer getSTORE_ID() {
        return this.STORE_ID;
    }
    public void setSTORE_ID(Integer STORE_ID) {
        this.STORE_ID = STORE_ID;
    }
    public String getDICT_TYPE() {
        return this.DICT_TYPE;
    }
    public void setDICT_TYPE(String DICT_TYPE) {
        this.DICT_TYPE = DICT_TYPE;
    }
    public String getITEM_EXT_STRING1() {
        return this.ITEM_EXT_STRING1;
    }
    public void setITEM_EXT_STRING1(String ITEM_EXT_STRING1) {
        this.ITEM_EXT_STRING1 = ITEM_EXT_STRING1;
    }
    public String getITEM_EXT_STRING2() {
        return this.ITEM_EXT_STRING2;
    }
    public void setITEM_EXT_STRING2(String ITEM_EXT_STRING2) {
        this.ITEM_EXT_STRING2 = ITEM_EXT_STRING2;
    }
    public String getITEM_NAME() {
        return this.ITEM_NAME;
    }
    public void setITEM_NAME(String ITEM_NAME) {
        this.ITEM_NAME = ITEM_NAME;
    }
    public String getINPUT_CODE3() {
        return this.INPUT_CODE3;
    }
    public void setINPUT_CODE3(String INPUT_CODE3) {
        this.INPUT_CODE3 = INPUT_CODE3;
    }
    public String getINPUT_CODE2() {
        return this.INPUT_CODE2;
    }
    public void setINPUT_CODE2(String INPUT_CODE2) {
        this.INPUT_CODE2 = INPUT_CODE2;
    }
    public Integer getLEVELS() {
        return this.LEVELS;
    }
    public void setLEVELS(Integer LEVELS) {
        this.LEVELS = LEVELS;
    }
    public String getITEM_CODE() {
        return this.ITEM_CODE;
    }
    public void setITEM_CODE(String ITEM_CODE) {
        this.ITEM_CODE = ITEM_CODE;
    }
    public Integer getLOCK_FLAG() {
        return this.LOCK_FLAG;
    }
    public void setLOCK_FLAG(Integer LOCK_FLAG) {
        this.LOCK_FLAG = LOCK_FLAG;
    }
    public Integer getDELETE_FLAG() {
        return this.DELETE_FLAG;
    }
    public void setDELETE_FLAG(Integer DELETE_FLAG) {
        this.DELETE_FLAG = DELETE_FLAG;
    }
    public Integer getEND_FLAG() {
        return this.END_FLAG;
    }
    public void setEND_FLAG(Integer END_FLAG) {
        this.END_FLAG = END_FLAG;
    }
    public Long getPARENT_ID() {
        return this.PARENT_ID;
    }
    public void setPARENT_ID(Long PARENT_ID) {
        this.PARENT_ID = PARENT_ID;
    }
    public String getDICT_ID() {
        return this.DICT_ID;
    }
    public void setDICT_ID(String DICT_ID) {
        this.DICT_ID = DICT_ID;
    }
    public Integer getITEM_SORT() {
        return this.ITEM_SORT;
    }
    public void setITEM_SORT(Integer ITEM_SORT) {
        this.ITEM_SORT = ITEM_SORT;
    }
    public String getITEM_EXT_STRING4() {
        return this.ITEM_EXT_STRING4;
    }
    public void setITEM_EXT_STRING4(String ITEM_EXT_STRING4) {
        this.ITEM_EXT_STRING4 = ITEM_EXT_STRING4;
    }
    public String getITEM_EXT_STRING5() {
        return this.ITEM_EXT_STRING5;
    }
    public void setITEM_EXT_STRING5(String ITEM_EXT_STRING5) {
        this.ITEM_EXT_STRING5 = ITEM_EXT_STRING5;
    }
    public String getITEM_EXT_STRING6() {
        return this.ITEM_EXT_STRING6;
    }
    public void setITEM_EXT_STRING6(String ITEM_EXT_STRING6) {
        this.ITEM_EXT_STRING6 = ITEM_EXT_STRING6;
    }
    public Integer getITEM_EXT_NUM1() {
        return this.ITEM_EXT_NUM1;
    }
    public void setITEM_EXT_NUM1(Integer ITEM_EXT_NUM1) {
        this.ITEM_EXT_NUM1 = ITEM_EXT_NUM1;
    }
    public Integer getITEM_EXT_NUM2() {
        return this.ITEM_EXT_NUM2;
    }
    public void setITEM_EXT_NUM2(Integer ITEM_EXT_NUM2) {
        this.ITEM_EXT_NUM2 = ITEM_EXT_NUM2;
    }
    public Integer getITEM_EXT_NUM3() {
        return this.ITEM_EXT_NUM3;
    }
    public void setITEM_EXT_NUM3(Integer ITEM_EXT_NUM3) {
        this.ITEM_EXT_NUM3 = ITEM_EXT_NUM3;
    }
    public String getITEM_EXT_STRING3() {
        return this.ITEM_EXT_STRING3;
    }
    public void setITEM_EXT_STRING3(String ITEM_EXT_STRING3) {
        this.ITEM_EXT_STRING3 = ITEM_EXT_STRING3;
    }
    public String getBAR_CODE() {
        return this.BAR_CODE;
    }
    public void setBAR_CODE(String BAR_CODE) {
        this.BAR_CODE = BAR_CODE;
    }
    public Date getCREATE_DATE() {
        return this.CREATE_DATE;
    }
    public void setCREATE_DATE(Date CREATE_DATE) {
        this.CREATE_DATE = CREATE_DATE;
    }
    public Date getMODIFY_DATE() {
        return this.MODIFY_DATE;
    }
    public void setMODIFY_DATE(Date MODIFY_DATE) {
        this.MODIFY_DATE = MODIFY_DATE;
    }

}
