package coder.aihui.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Keep;
import org.greenrobot.greendao.annotation.Property;
import org.greenrobot.greendao.annotation.Transient;

import java.util.List;

import coder.aihui.data.normalbean.PartsBean;
import coder.aihui.util.GsonUtil;

/**
 * Entity mapped to table PUR__CONTRACT__PLAN.
 */

@Entity
public class PUR_CONTRACT_PLAN   {

    @Id
    @Property(nameInDb = "HTMX__ID")
    private Long           HTMX_ID;
    private Integer        CONTRACT_ID;
    private String         CONTRACT_NUM;
    private Integer        PLAN_ID;
    private Integer        DEPT_ID;
    private String         DEPT_NAME;
    private String         WZMC;
    private Integer        YSSL;
    private Integer        MCGGID;
    private String         GYSMC;
    private String         GGXH;
    private java.util.Date CREATE_TIME;
    private java.util.Date CHECK_TIME;
    private String         CHECK_LISTNUM;
    private Integer        CHECK_SL;
    private Integer        CHECK_STATUS;
    private String         DH_ID;
    private String         YSR_IDS;
    private String         AZGCS;
    private Integer        BXQ;
    private String         GCJK;
    private String         BRAND;
    @Transient
    private List<PartsBean> PARTS;

    @Property(nameInDb = "PARTS")
    private String          PARTS_STRING;
    private String          ZCZH;

    private String QSDQSJ;





    @Keep
    public PUR_CONTRACT_PLAN(Long HTMX_ID, Integer CONTRACT_ID, String CONTRACT_NUM, Integer PLAN_ID,
                             Integer DEPT_ID, String DEPT_NAME, String WZMC, Integer YSSL, Integer MCGGID, String GYSMC,
                             String GGXH, java.util.Date CREATE_TIME, java.util.Date CHECK_TIME, String CHECK_LISTNUM,
                             Integer CHECK_SL, Integer CHECK_STATUS, String DH_ID, String YSR_IDS, String AZGCS,
                             Integer BXQ, String GCJK, String BRAND, List<PartsBean> PARTS, String ZCZH, String QSDQSJ) {
        this.HTMX_ID = HTMX_ID;
        this.CONTRACT_ID = CONTRACT_ID;
        this.CONTRACT_NUM = CONTRACT_NUM;
        this.PLAN_ID = PLAN_ID;
        this.DEPT_ID = DEPT_ID;
        this.DEPT_NAME = DEPT_NAME;
        this.WZMC = WZMC;
        this.YSSL = YSSL;
        this.MCGGID = MCGGID;
        this.GYSMC = GYSMC;
        this.GGXH = GGXH;
        this.CREATE_TIME = CREATE_TIME;
        this.CHECK_TIME = CHECK_TIME;
        this.CHECK_LISTNUM = CHECK_LISTNUM;
        this.CHECK_SL = CHECK_SL;
        this.CHECK_STATUS = CHECK_STATUS;
        this.DH_ID = DH_ID;
        this.YSR_IDS = YSR_IDS;
        this.AZGCS = AZGCS;
        this.BXQ = BXQ;
        this.GCJK = GCJK;
        this.BRAND = BRAND;
        this.PARTS_STRING = GsonUtil.parseListToJson(PARTS);
        this.ZCZH = ZCZH;
        this.QSDQSJ = QSDQSJ;
    }







    @Generated(hash = 1968149911)
    public PUR_CONTRACT_PLAN(Long HTMX_ID, Integer CONTRACT_ID, String CONTRACT_NUM, Integer PLAN_ID, Integer DEPT_ID,
            String DEPT_NAME, String WZMC, Integer YSSL, Integer MCGGID, String GYSMC, String GGXH,
            java.util.Date CREATE_TIME, java.util.Date CHECK_TIME, String CHECK_LISTNUM, Integer CHECK_SL,
            Integer CHECK_STATUS, String DH_ID, String YSR_IDS, String AZGCS, Integer BXQ, String GCJK, String BRAND,
            String PARTS_STRING, String ZCZH, String QSDQSJ) {
        this.HTMX_ID = HTMX_ID;
        this.CONTRACT_ID = CONTRACT_ID;
        this.CONTRACT_NUM = CONTRACT_NUM;
        this.PLAN_ID = PLAN_ID;
        this.DEPT_ID = DEPT_ID;
        this.DEPT_NAME = DEPT_NAME;
        this.WZMC = WZMC;
        this.YSSL = YSSL;
        this.MCGGID = MCGGID;
        this.GYSMC = GYSMC;
        this.GGXH = GGXH;
        this.CREATE_TIME = CREATE_TIME;
        this.CHECK_TIME = CHECK_TIME;
        this.CHECK_LISTNUM = CHECK_LISTNUM;
        this.CHECK_SL = CHECK_SL;
        this.CHECK_STATUS = CHECK_STATUS;
        this.DH_ID = DH_ID;
        this.YSR_IDS = YSR_IDS;
        this.AZGCS = AZGCS;
        this.BXQ = BXQ;
        this.GCJK = GCJK;
        this.BRAND = BRAND;
        this.PARTS_STRING = PARTS_STRING;
        this.ZCZH = ZCZH;
        this.QSDQSJ = QSDQSJ;
    }







    @Generated(hash = 1500274075)
    public PUR_CONTRACT_PLAN() {
    }





   

    public Long getHTMX_ID() {
        return this.HTMX_ID;
    }

    public void setHTMX_ID(Long HTMX_ID) {
        this.HTMX_ID = HTMX_ID;
    }

    public Integer getCONTRACT_ID() {
        return this.CONTRACT_ID;
    }

    public void setCONTRACT_ID(Integer CONTRACT_ID) {
        this.CONTRACT_ID = CONTRACT_ID;
    }

    public String getCONTRACT_NUM() {
        return this.CONTRACT_NUM;
    }

    public void setCONTRACT_NUM(String CONTRACT_NUM) {
        this.CONTRACT_NUM = CONTRACT_NUM;
    }

    public Integer getPLAN_ID() {
        return this.PLAN_ID;
    }

    public void setPLAN_ID(Integer PLAN_ID) {
        this.PLAN_ID = PLAN_ID;
    }

    public Integer getDEPT_ID() {
        return this.DEPT_ID;
    }

    public void setDEPT_ID(Integer DEPT_ID) {
        this.DEPT_ID = DEPT_ID;
    }

    public String getDEPT_NAME() {
        return this.DEPT_NAME;
    }

    public void setDEPT_NAME(String DEPT_NAME) {
        this.DEPT_NAME = DEPT_NAME;
    }

    public String getWZMC() {
        return this.WZMC;
    }

    public void setWZMC(String WZMC) {
        this.WZMC = WZMC;
    }

    public Integer getYSSL() {
        return this.YSSL;
    }

    public void setYSSL(Integer YSSL) {
        this.YSSL = YSSL;
    }

    public Integer getMCGGID() {
        return this.MCGGID;
    }

    public void setMCGGID(Integer MCGGID) {
        this.MCGGID = MCGGID;
    }

    public String getGYSMC() {
        return this.GYSMC;
    }

    public void setGYSMC(String GYSMC) {
        this.GYSMC = GYSMC;
    }

    public String getGGXH() {
        return this.GGXH;
    }

    public void setGGXH(String GGXH) {
        this.GGXH = GGXH;
    }

    public java.util.Date getCREATE_TIME() {
        return this.CREATE_TIME;
    }

    public void setCREATE_TIME(java.util.Date CREATE_TIME) {
        this.CREATE_TIME = CREATE_TIME;
    }

    public java.util.Date getCHECK_TIME() {
        return this.CHECK_TIME;
    }

    public void setCHECK_TIME(java.util.Date CHECK_TIME) {
        this.CHECK_TIME = CHECK_TIME;
    }

    public String getCHECK_LISTNUM() {
        return this.CHECK_LISTNUM;
    }

    public void setCHECK_LISTNUM(String CHECK_LISTNUM) {
        this.CHECK_LISTNUM = CHECK_LISTNUM;
    }

    public Integer getCHECK_SL() {
        return this.CHECK_SL;
    }

    public void setCHECK_SL(Integer CHECK_SL) {
        this.CHECK_SL = CHECK_SL;
    }

    public Integer getCHECK_STATUS() {
        return this.CHECK_STATUS;
    }

    public void setCHECK_STATUS(Integer CHECK_STATUS) {
        this.CHECK_STATUS = CHECK_STATUS;
    }

    public String getDH_ID() {
        return this.DH_ID;
    }

    public void setDH_ID(String DH_ID) {
        this.DH_ID = DH_ID;
    }

    public String getYSR_IDS() {
        return this.YSR_IDS;
    }

    public void setYSR_IDS(String YSR_IDS) {
        this.YSR_IDS = YSR_IDS;
    }

    public String getAZGCS() {
        return this.AZGCS;
    }

    public void setAZGCS(String AZGCS) {
        this.AZGCS = AZGCS;
    }

    public Integer getBXQ() {
        return this.BXQ;
    }

    public void setBXQ(Integer BXQ) {
        this.BXQ = BXQ;
    }

    public String getGCJK() {
        return this.GCJK;
    }

    public void setGCJK(String GCJK) {
        this.GCJK = GCJK;
    }

    public String getBRAND() {
        return this.BRAND;
    }

    public void setBRAND(String BRAND) {
        this.BRAND = BRAND;
    }

    public String getPARTS_STRING() {
        return PARTS_STRING;
    }



    public void setPARTS_STRING(String PARTS_STRING) {
        this.PARTS_STRING = PARTS_STRING;
    }


    public String getZCZH() {
        return this.ZCZH;
    }

    public void setZCZH(String ZCZH) {
        this.ZCZH = ZCZH;
    }

    public String getQSDQSJ() {
        return this.QSDQSJ;
    }

    public void setQSDQSJ(String QSDQSJ) {
        this.QSDQSJ = QSDQSJ;
    }

    public List<PartsBean> getPARTS() {
        return PARTS;
    }

    public void setPARTS(List<PartsBean> PARTS) {
        this.PARTS = PARTS;
    }
}
