package coder.aihui.data.bean;

import com.mcxtzhang.indexlib.IndexBar.bean.BaseIndexPinyinBean;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;
import org.greenrobot.greendao.annotation.Transient;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table SYS__USER.
 */
@Entity
public class SYS_USER extends BaseIndexPinyinBean {
    @Id
    @Property(nameInDb = "USER__ID")
    private Long USER_ID;
    private Integer USER_DEPT_ID;
    private String USER_ACCOUNT;
    private String USER_PSWD;
    private String USER_CODE;
    private String USER_NAME;
    private Integer USER_SEX;
    private String USER_PHONE;
    private Integer USER_ISDEL;
    private String USER_PY;
    private String USER_WB;
    private String HOSPITAL_NAME;
    private String USER_FUNCS;

    @Transient
    private boolean IS_CHECKED;
    
    
    /*public SYS_USER(JSONObject json) {
        try {
			this.USER_ID = json.getLong("USER_ID");
			this.USER_DEPT_ID = getInt(json.getString("USER_DEPT_ID"));
	        this.USER_ACCOUNT = json.getString("USER_ACCOUNT");
	        this.USER_PSWD = json.getString("USER_PSWD");
	        this.USER_CODE = json.getString("USER_CODE");
	        this.USER_NAME = json.getString("USER_NAME");
	        this.USER_SEX = getInt(json.getString("USER_SEX"));
	        this.USER_PHONE = json.getString("USER_PHONE");
	        this.USER_ISDEL = getInt(json.getString("USER_ISDEL"));
	        this.USER_PY = json.getString("USER_PY");
	        this.USER_WB = json.getString("USER_WB");
	        this.HOSPITAL_NAME = json.getString("HOSPITAL_NAME");
            this.USER_FUNCS = json.getString("USER_FUNCS");

        } catch (JSONException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }*/


    @Generated(hash = 1297328701)
    public SYS_USER(Long USER_ID, Integer USER_DEPT_ID, String USER_ACCOUNT, String USER_PSWD,
            String USER_CODE, String USER_NAME, Integer USER_SEX, String USER_PHONE, Integer USER_ISDEL,
            String USER_PY, String USER_WB, String HOSPITAL_NAME, String USER_FUNCS) {
        this.USER_ID = USER_ID;
        this.USER_DEPT_ID = USER_DEPT_ID;
        this.USER_ACCOUNT = USER_ACCOUNT;
        this.USER_PSWD = USER_PSWD;
        this.USER_CODE = USER_CODE;
        this.USER_NAME = USER_NAME;
        this.USER_SEX = USER_SEX;
        this.USER_PHONE = USER_PHONE;
        this.USER_ISDEL = USER_ISDEL;
        this.USER_PY = USER_PY;
        this.USER_WB = USER_WB;
        this.HOSPITAL_NAME = HOSPITAL_NAME;
        this.USER_FUNCS = USER_FUNCS;
    }


    @Generated(hash = 2015099698)
    public SYS_USER() {
    }

    @Override
    public String getTarget() {
        return USER_NAME;
    }


    public Long getUSER_ID() {
        return this.USER_ID;
    }


    public void setUSER_ID(Long USER_ID) {
        this.USER_ID = USER_ID;
    }


    public Integer getUSER_DEPT_ID() {
        return this.USER_DEPT_ID;
    }


    public void setUSER_DEPT_ID(Integer USER_DEPT_ID) {
        this.USER_DEPT_ID = USER_DEPT_ID;
    }


    public String getUSER_ACCOUNT() {
        return this.USER_ACCOUNT;
    }


    public void setUSER_ACCOUNT(String USER_ACCOUNT) {
        this.USER_ACCOUNT = USER_ACCOUNT;
    }


    public String getUSER_PSWD() {
        return this.USER_PSWD;
    }


    public void setUSER_PSWD(String USER_PSWD) {
        this.USER_PSWD = USER_PSWD;
    }


    public String getUSER_CODE() {
        return this.USER_CODE;
    }


    public void setUSER_CODE(String USER_CODE) {
        this.USER_CODE = USER_CODE;
    }


    public String getUSER_NAME() {
        return this.USER_NAME;
    }


    public void setUSER_NAME(String USER_NAME) {
        this.USER_NAME = USER_NAME;
    }


    public Integer getUSER_SEX() {
        return this.USER_SEX;
    }


    public void setUSER_SEX(Integer USER_SEX) {
        this.USER_SEX = USER_SEX;
    }


    public String getUSER_PHONE() {
        return this.USER_PHONE;
    }


    public void setUSER_PHONE(String USER_PHONE) {
        this.USER_PHONE = USER_PHONE;
    }


    public Integer getUSER_ISDEL() {
        return this.USER_ISDEL;
    }


    public void setUSER_ISDEL(Integer USER_ISDEL) {
        this.USER_ISDEL = USER_ISDEL;
    }


    public String getUSER_PY() {
        return this.USER_PY;
    }


    public void setUSER_PY(String USER_PY) {
        this.USER_PY = USER_PY;
    }


    public String getUSER_WB() {
        return this.USER_WB;
    }


    public void setUSER_WB(String USER_WB) {
        this.USER_WB = USER_WB;
    }


    public String getHOSPITAL_NAME() {
        return this.HOSPITAL_NAME;
    }


    public void setHOSPITAL_NAME(String HOSPITAL_NAME) {
        this.HOSPITAL_NAME = HOSPITAL_NAME;
    }


    public String getUSER_FUNCS() {
        return this.USER_FUNCS;
    }


    public void setUSER_FUNCS(String USER_FUNCS) {
        this.USER_FUNCS = USER_FUNCS;
    }

    public boolean IS_CHECKED() {
        return IS_CHECKED;
    }

    public void setIS_CHECKED(boolean IS_CHECKED) {
        this.IS_CHECKED = IS_CHECKED;
    }
}
