package coder.aihui.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table SYS__PARAM.
 */
@Entity
public class SYS_PARAM  {

    @Id
    @Property(nameInDb = "PARAM__ID")
    private Long   PARAM_ID;
    private String PARAM_KEY;
    private String PARAM_VALUE;
    private String PARAM_REMARK;
    @Generated(hash = 226884409)
    public SYS_PARAM(Long PARAM_ID, String PARAM_KEY, String PARAM_VALUE, String PARAM_REMARK) {
        this.PARAM_ID = PARAM_ID;
        this.PARAM_KEY = PARAM_KEY;
        this.PARAM_VALUE = PARAM_VALUE;
        this.PARAM_REMARK = PARAM_REMARK;
    }
    @Generated(hash = 1336801741)
    public SYS_PARAM() {
    }
    public Long getPARAM_ID() {
        return this.PARAM_ID;
    }
    public void setPARAM_ID(Long PARAM_ID) {
        this.PARAM_ID = PARAM_ID;
    }
    public String getPARAM_KEY() {
        return this.PARAM_KEY;
    }
    public void setPARAM_KEY(String PARAM_KEY) {
        this.PARAM_KEY = PARAM_KEY;
    }
    public String getPARAM_VALUE() {
        return this.PARAM_VALUE;
    }
    public void setPARAM_VALUE(String PARAM_VALUE) {
        this.PARAM_VALUE = PARAM_VALUE;
    }
    public String getPARAM_REMARK() {
        return this.PARAM_REMARK;
    }
    public void setPARAM_REMARK(String PARAM_REMARK) {
        this.PARAM_REMARK = PARAM_REMARK;
    }


}
